### ISSUE TITLE
Should remove input.input for validation error

### ISSUE THREAD

**Issue by viennv1709** [doug-martin/nestjs-query#1020]
**Is your feature request related to a problem? Please describe.**
I don't want validation message returned that includes input.input
![image](https://user-images.githubusercontent.com/5088270/112795291-85d6bd80-9092-11eb-9a41-17e2eb5ca28b.png)

**Describe the solution you'd like**
Want to remove input.input in validation message

**Comment by viennv1709** [comment]
@doug-martin @smolinari Do you guys have any idea about that?

**Comment by smolinari** [comment]
What are you doing, when you get that error?

Scott

**Comment by viennv1709** [comment]
Actually I don't want to use `replace('input.input', '')` in client code. I just want to return messages without including `input.input`. Because the library's wrapping input from user in `input.input` and use `ValidateNested`

**Comment by smolinari** [comment]
I'm seeing this error too now. Looking for the reason. 

Scott

**Comment by smolinari** [comment]
The way it looks, this is either a problem in Nest or class-validator. 

Scott

**Comment by smolinari** [comment]
This is where the validation pipe is tested in Nest. Interesting it's missing the key altogether. 

https://github.com/nestjs/nest/blob/097afb0884415ee98910d93380b3eb6592cfb03c/integration/graphql-code-first/e2e/pipes.spec.ts#L19

I think this can be closed. Now the question is, what is going wrong in Nest? I'll have a look later and maybe write up an issue, if I can reproduce it.

Scott

**Comment by smolinari** [comment]
I'm going to have to give up on this. The tests all run properly and when I set up Nest to be linked locally, I am ending up with different errors. So, can't troubleshoot. Sorry. 🤷 

Scott

**Comment by smolinari** [comment]
And, it's definitely Nest's validation pipe. It's adding the paths. Correct or not, that is the design.

Scott
