### ISSUE TITLE
createOne and createMany in resolver pass undefined to service if using custom resolver and custom service

### ISSUE THREAD

**Issue by viennv1709** [doug-martin/nestjs-query#1025]
**Describe the bug**
createOne and createMany in resolver pass undefined to service if using custom resolver and custom service

**To Reproduce**
This is what I debugged to see. it's not `input.input.input`, it's `input.input.apiKey`:
![image](https://user-images.githubusercontent.com/5088270/112960227-68772180-916e-11eb-82ed-6b8188a984cd.png)

**Comment by viennv1709** [comment]
@doug-martin @smolinari Sometimes it works well, sometimes it doesn't work
It should be like this:
![image](https://user-images.githubusercontent.com/5088270/113481496-1ca4df00-94c4-11eb-8b67-5e1c9fd78ce6.png)

**Comment by viennv1709** [comment]
It's very strange. Sometimes it maps correctly to CO = ApiKeyInputDto in this case, but sometimes it doesn't map

**Comment by viennv1709** [comment]
It seems that it doesn't support enum

**Comment by viennv1709** [comment]
I found the issue that is when I use asynchronous validator for input dto.

**Comment by viennv1709** [comment]
@doug-martin @smolinari This is my custom validator. It doesn't work if I return `Promise<boolean>`. It works only if I return `boolean`
```typescript
import { UserService } from './user.service';
import {
  buildMessage,
  getFromContainer,
  ValidateBy,
  ValidationOptions,
} from 'class-validator';

export function IsUserAlreadyExist(
  validationOptions?: ValidationOptions,
): PropertyDecorator {
  return ValidateBy(
    {
      name: 'isUserAlreadyExist',
      async: true,
      validator: {
        validate: async (email: string) => {
          const userService = getFromContainer(UserService);
          const user = await userService.findByEmail(email);
          return !user;
        },
        defaultMessage: buildMessage(
          (eachPrefix) => eachPrefix + '$property already exists',
          validationOptions,
        ),
      },
    },
    validationOptions,
  );
}

```

**Comment by smolinari** [comment]
@viennv1709 - I've never done a custom validator myself, but what you are doing doesn't look like what `class-validator` is showing in their docs. https://github.com/typestack/class-validator#custom-validation-decorators

If you are having trouble with class-validator, I'd suggest you find their community and ask questions there. 

Scott

**Comment by viennv1709** [comment]
@smolinari Yes, I'm using `class-validator`. The issue come from `nestjs-query` not from `class-validator`. If I use async custom validator, then the code in `hook-args.decorator.ts` file work incorrectly 
```typescript
function transformValue<T>(value: T, type?: Class<T>): T {
  if (type && !(value instanceof type)) {
    return plainToClass<T, unknown>(type, value);
  }
  return value;
}
```

**Comment by smolinari** [comment]
Can you offer a minimum reproduction please?

Scott

**Comment by viennv1709** [comment]
You can see it here. https://bitbucket.org/inspiron1709/nest-example/src/master/

**Comment by viennv1709** [comment]
@smolinari Please try to create a user

**Comment by smolinari** [comment]
@viennv1709 - I have it working. 

UserModule:
```ts
@Module({
  imports: [
    NestjsQueryGraphQLModule.forFeature({
      imports: [ NestjsQueryTypegooseModule.forFeature([ UserEntity ]) ],
      resolvers: [],
      dtos: [
        {
          DTOClass: UserDto,
          UpdateDTOClass: UserInputDto,
          CreateDTOClass: UserInputDto
        }
      ]
    }),
  ],
  providers: [UserService, UserResolver],
  exports: [UserService],
})
export class UserModule {}
```
UserResolver:
```ts
@Resolver()
export class UserResolver extends CRUDResolver(UserDto, {
  CreateDTOClass: UserInputDto,
  UpdateDTOClass: UserInputDto,
  read: { one: { name: 'findUserById' }, many: { name: 'findUsers' } },
  create: { one: { name: 'createUser' }, many: { disabled: true } },
  update: { one: { name: 'updateUser' }, many: { disabled: true } },
  delete: { one: { name: 'deleteUser' }, many: { disabled: true } },
}) {
  constructor(@InjectQueryService(UserEntity) readonly service: QueryService<UserEntity>) {
    super(service);
  }

  // @Query(() => UserDto, { name: 'findUserByEmail' })
  // async findByEmail(
  //   @HookArgs() input: FindUserByEmailArgs,
  //   @AuthorizerFilter() authorizeFilter?: Filter<UserDto>,
  // ): Promise<UserDto | undefined> {
  //   return this.userService.findByEmail(input.email, {
  //     filter: authorizeFilter,
  //   });
  // }
}
```

**Comment by viennv1709** [comment]
@smolinari Please pull latest code. I updated code to reproduce it

**Comment by smolinari** [comment]
@viennv1709 - Fix your resolver as I have it above and try it.

Scott

**Comment by viennv1709** [comment]
@smolinari No, if I do it like you have. I can't call findByEmail in my custom service

**Comment by viennv1709** [comment]
@smolinari And it doesn't fix the issue I have as well

**Comment by smolinari** [comment]
Ok. A couple of things. 

1. Doing validation like you are attempting is the wrong place IMHO. You should simply do it in your service. Notice too how I've built up the UserService. Throwing in the service is better, because it's much more obvious and does it only for the one function. Otherwise you'd need a different create and update DTO. (you wouldn't want an update to fail because of the validation looking to see if the use exists and does, right?) 

`UserInputError` is from `apollo-server-errors`.

```ts
@Assembler(UserDto, UserEntity)
export class UserAssembler extends ClassTransformerAssembler<UserDto, UserEntity> { }

@Injectable()
@QueryService(UserDto)
export class UserService extends AssemblerQueryService<UserDto, UserEntity> {
  constructor(
    readonly assembler: UserAssembler,
    @InjectQueryService(UserEntity) private readonly service: QueryService<UserEntity>,
  ) {
    super(assembler, service);
  }
  
  async createOne(
    record: UserDto,
  ): Promise<UserEntity> {
    const user = await this.service.query({ filter: { email: { eq: record.email } } })
    if (user.length > 0) {
      throw new UserInputError('This user already exists.')
    }
    return this.service.createOne(record);
  }
  
  async findByEmail(
    email: string
  ): Promise<UserEntity | null> {
    console.log('email: ', email)
    const user = await this.service.query({ filter: { email: { eq: email } } })
    console.log('user: ', user[0])
    if (user.length >= 1) return user[0]
  }
```
2. Remove the HTTP exception filter in your AppModule. This causes any error to be a 500. 

```ts

  // providers: [
  //   {
  //     provide: APP_FILTER,
  //     useClass: HttpExceptionFilter,
  //   },
  // ],
})
export class AppModule {}
```

3. User Resover: 

```ts
@Resolver()
export class UserResolver extends CRUDResolver(UserDto, {
  read: { one: { name: 'findUserById' }, many: { name: 'findUsers' } },
  create: { one: { name: 'createUser' }, many: { disabled: true } },
  update: { one: { name: 'updateUser' }, many: { disabled: true } },
  delete: { one: { name: 'deleteUser' }, many: { disabled: true } },
}) {
  constructor(readonly service: UserService) {
    super(service);
  }

  @Query(() => UserDto, { name: 'findUserByEmail', nullable: true })
  async findByEmail(
    @HookArgs() input: FindUserByEmailArgs,
    // @AuthorizerFilter() authorizeFilter?: Filter<UserDto>,
  ): Promise<UserDto | null> {
    return this.service.findByEmail(input.email
    );
  }
}
```

Scott

**Comment by viennv1709** [comment]
OK. Thank you for your help. Although it's an error but I agree with you to check it in services
