### ISSUE TITLE
query-typeorm: Do not ignore relations of relation anymore

### ISSUE THREAD

**Issue by steinroe** [doug-martin/nestjs-query#1041]
**Is your feature request related to a problem? Please describe.**
This is a follow up of the use-case / workaround I described in #797. 

Basically, it would be great to not ignore relations of the relation in the where builder anymore:
```typescript
// where.builder.ts
private withRelationFilter<T extends keyof Entity, Where extends WhereExpression>(
    where: Where,
    field: T,
    cmp: Filter<Entity[T]>,
  ): Where {
    return where.andWhere(
      new Brackets((qb) => {
        const relationWhere = new WhereBuilder<Entity[T]>();
        // for now ignore relations of relations.
        return relationWhere.build(qb, cmp, [], field as string);
      }),
    );
  }
```
This is an edge case, since is only occurs when you are misusing the query builder, but it would be great to remove that limitation.

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?

Yes

**Describe the solution you'd like**
Removing that limitation would make the query builder really powerful and flexible.

**Additional context**
I would also be happy to remove that limitation myself, but since this is an edge case and getting the relation names of the relation in that place will likely have an impact in the query builders, I would like your thoughts on it first @doug-martin.

**Comment by doug-martin** [comment]
@steinroe this is on the todo list, but my concern is not always having access to the relation entity in all persistence packages. I have not looked into this directly, if you want to look at getting the persistence `QueryServices` to support filtering on relations of relations adding support in the graphql layer should be straight forward.

**Comment by GP4cK** [comment]
I'm trying to look into the `query-typeorm` first. I believe we would need to make the following changes (please correct me if I'm wrong)
1. `getReferencedRelations`: instead of returning an array of relation names, it should return an object with the nested relations
ex: if we have a structure like project -> todo -> subTask, getReferencedRelations() would return  
```ts
{
  todo: {
    subTask: {}
  }
}
// instead of 
['todo']
```
2. `applyRelationJoins` should be recursive to handle the nested relations
3. change all the methods in the class `WhereBuilder` to take the new object instead of an string[] for the relations

@doug-martin if I made a PR for `query-typeorm` only, would you consider it?

**Comment by awHamer** [comment]
Any updates on this? It would be super nice to have it

**Comment by steinroe** [comment]
@GP4cK Do you think it is possible to return
```
{
  todo: {
    subTask: {}
  }
}
```
directly on the project level? I was thinking of an recursive approach, where each relation only checks what first-level relations are referenced.

**Comment by GP4cK** [comment]
Yes it's definitely better to only query the relations used in the filter.

> Did you make any progress?

So far, we've managed to tweak our logic and only make use of the first level relations. But I'd be happy to help with the implementation.

**Comment by rbiggers** [comment]
I need this feature as well.

@GP4cK would you be interested in collaborating?

@doug-martin would you mind pointing us in the right direction? Where to start, files, functions, etc. Any information you can provide would be greatly appreciated. 

Thank you

**Comment by GP4cK** [comment]
@rbiggers I'm going to be pretty busy with work until mid September but after that, sure.
Just need a little directions from doug

**Comment by rbiggers** [comment]
@GP4cK Ok great if you could give me a date that would work for you I can check back then. In the meantime I will look into what I can do to get us there faster

**Comment by GP4cK** [comment]
@rbiggers basically after October 1st

**Comment by john-mcinall** [comment]
Has anyone been working on this? I am about to start an implementation of this and don't want to just repeat work that has already been done :)

**Comment by rbiggers** [comment]
@john-mcinall I am not aware of any work that has been started on this.

**Comment by steinroe** [comment]
me neither

**Comment by steinroe** [comment]
I did an initial implementation in #1340 and would love to get some feedback on it
