### ISSUE TITLE
Error: Cannot determine a GraphQL output type

### ISSUE THREAD

**Issue by SirMishaa** [doug-martin/nestjs-query#1047]
**Describe the bug**

Hello, 

I have an error message that I don't quite understand.
According to my research, this is because of my relationship, GraphQL does not seem to "see" the input that should be automatically created by nestjs-query. 

My mistake may be a bit stupid, I'm sorry if it is, but I've been searching for a few hours and I can't find anything.

**Expected behavior**
It should work 

**Desktop (please complete the following information):**
 - Node v14.14
 - Nestjs-query v0.25
 - nestjs/graphql v7.9.8

**Additional context**

Error message : ``Error: Cannot determine a GraphQL output type for the "submittedProducts"``

product.module.ts : 
```ts
@Module({
  imports: [
    NestjsQueryGraphQLModule.forFeature({
      imports: [
        NestjsQueryTypeOrmModule.forFeature([
          Product,
          ProductCategory,
          ProductImage,
          Brand,
        ]),
      ],
      resolvers: [
        { DTOClass: ProductDto, EntityClass: Product },
        { DTOClass: ProductCategoryDto, EntityClass: ProductCategory },
        { DTOClass: ProductImageDto, EntityClass: ProductImage },
        { DTOClass: BrandDto, EntityClass: Brand },
      ],
    }),
  ],
  providers: [],
})
export class ProductModule {}
```
user.module.ts : 
```ts
@Module({
  imports: [
    NestjsQueryGraphQLModule.forFeature({
      imports: [NestjsQueryTypeOrmModule.forFeature([User])],
      resolvers: [{ DTOClass: UserDto, EntityClass: User }],
    }),
  ],
  controllers: [UserController],
  providers: [AppLogger, MailerModule, FileService, ConfigService],
})
export class UserModule {}
```
user.entity.ts :
```ts
@Entity()
@Unique(['username', 'providerId', 'mail'])
export class User extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ type: 'varchar', length: 255, nullable: true, unique: true })
  providerId?: string;

  @Column({ type: 'varchar', length: 255, unique: true })
  mail!: string;

  @Column({ type: 'varchar', length: 12, unique: true })
  username!: string;

  @Column({ type: 'varchar', length: 255, nullable: true })
  avatar?: string;

  @Column({ type: 'timestamptz', default: () => 'CURRENT_TIMESTAMP' })
  createdAt!: Date;

  @Column({ type: 'timestamptz', nullable: true })
  lastUpdateUsername?: Date;

  @OneToMany(() => Product, (product) => product.submittedBy)
  submittedProducts!: Array<Product>;
}
``` 
And finally, user.dto.ts : 
```ts
import { Product } from '@domain/product/model/product.entity';
import { FilterableField } from '@nestjs-query/query-graphql';
import { Field, ObjectType } from '@nestjs/graphql';

@ObjectType('User')
export class UserDto {
  @FilterableField(() => String)
  id!: string;

  @FilterableField(() => String)
  providerId?: string;

  @FilterableField(() => String)
  mail!: string;

  @FilterableField(() => String)
  username!: string;

  @FilterableField(() => String)
  avatar?: string;

  @FilterableField(() => String)
  createdAt!: Date;

  @FilterableField(() => String)
  lastUpdateUsername?: Date;

  @Field(() => [Product])
  submittedProducts!: Array<Product>;
}
```

Thank you very much if anyone can help me. ❤
Sorry to waste your time if the answer is silly.

I appreciate it.
Sincerely.

**Comment by SirMishaa** [comment]
I specify that I have of course a DTO for product. 
```ts
@ObjectType('Product')
export class ProductDto {
  @FilterableField(() => String)
  id!: string;

  @Field(() => Brand)
  brand!: Brand;

  @Field(() => [ProductImage])
  images!: Array<ProductImage>;

  @FilterableField(() => String)
  name!: string;

  @FilterableField(() => String)
  releaseDate!: Date;

  @FilterableField(() => Number)
  fiabilityScore?: number;

  @FilterableField(() => String)
  coverImage?: string;

  @FilterableField(() => Number)
  price?: number;

  @FilterableField(() => String)
  source?: string;

  @Field(() => User)
  submittedBy?: User;

  @FilterableField(() => String)
  description!: string;

  @Field(() => [ProductCategory])
  productCategories!: Array<ProductCategory>;

  @FilterableField(() => String)
  createdAt!: Date;
}
```

I really can't see the source of my error.

**Comment by mwoelk** [comment]
Try using [Relation decorators](https://doug-martin.github.io/nestjs-query/docs/graphql/relations) instead of fields.

**Comment by SirMishaa** [comment]
> 
> 
> Try using [Relation decorators](https://doug-martin.github.io/nestjs-query/docs/graphql/relations) instead of fields.

Like something like that ? : 
```ts
https://github.com/doug-martin/nestjs-query/issues/1047#issuecomment-814451126
```

**Comment by SirMishaa** [comment]
> 
> 
> Try using [Relation decorators](https://doug-martin.github.io/nestjs-query/docs/graphql/relations) instead of fields.

Indeed, this is working. Thanks a lot!

Just to be sure, do I have to do something like this? 
```ts
@ObjectType('Product')
@FilterableUnPagedRelation('images', () => ProductImageDto)
@FilterableUnPagedRelation('productCategories', () => ProductCategoryDto)
@FilterableRelation('submittedBy', () => UserDto)
@FilterableRelation('brand', () => BrandDto)
export class ProductDto {
  @FilterableField(() => String)
  id!: string;

  brand!: Brand;

  images!: Array<ProductImage>;

  @FilterableField(() => String)
  name!: string;

  @FilterableField(() => String)
  releaseDate!: Date;

  @FilterableField(() => Number)
  fiabilityScore?: number;

  @FilterableField(() => String)
  coverImage?: string;

  @FilterableField(() => Number)
  price?: number;

  @FilterableField(() => String)
  source?: string;

  submittedBy?: User;

  @FilterableField(() => String)
  description!: string;

  productCategories!: Array<ProductCategory>;

  @FilterableField(() => String)
  createdAt!: Date;
}
```

Because I see that in the documentation you seem to use ID in the class. I have to do the same thing ? 
(From documentation) : 
```ts
import { FilterableField, Relation } from '@nestjs-query/query-graphql';
import { ObjectType, ID, GraphQLISODateTime } from '@nestjs/graphql';
import { TodoItemDTO } from '../todo-item/todo-item.dto.ts';

@ObjectType('SubTask')
@Relation('todoItem', () => TodoItemDTO, { disableRemove: true })
export class SubTaskDTO {
  @FilterableField(() => ID)
  id!: string;

  @FilterableField()
  title!: string;

  @FilterableField()
  completed!: boolean;

  @FilterableField(() => GraphQLISODateTime)
  created!: Date;

  @FilterableField(() => GraphQLISODateTime)
  updated!: Date;

  @FilterableField()
  todoItemId!: string; // Here, why this is an ID ? It should not be a relation to TodoItem ? Like todoItem: TodoItem
}
```

**Comment by doug-martin** [comment]
@SirMishaa the `id` is not required for the relation to work. For the `relation` to work out of the box it just needs to match a relation on your entity. The example in question included the `todoItemId` just so you can filter on it directly (a relic from before filterable relations)

**Comment by SirMishaa** [comment]
Okay, thanks for the explanation. I'm just discovering nestjs-query and I have to admit that it's so handy, the work done is incredible.

I have one last question, in the case of a mandatory relationship, for example to create a ``product``, it must have a mandatory ``brand``. How do I do this?

I have defined the relationship well, but when I use the mutation created by nestjs-query, I have no possibility to specify a brand.

![image](https://user-images.githubusercontent.com/42717232/113859160-e0fc6480-97a4-11eb-98a8-87ab1c050406.png)

Here's, you can see that I don't have the ``brand`` field, even if it's mandatory and needed to create my ``product``. 

Am I doing something wrong? 

Here's the link of GraphQL schema if needed : https://gist.github.com/SirMishaa/39fbc6c6cdfd976b6a1f8de8b4e06f3c

**Comment by doug-martin** [comment]
@SirMishaa `nestjs-query` doesn't currently take a stand on this, however you could create an input DTO that contains the brand identifier either the of the field on the `entity` (e.g. `brandId`). 

Like this [`SubTaskEntity`](https://github.com/doug-martin/nestjs-query/blob/master/examples/typeorm/src/sub-task/sub-task.entity.ts#L27-L35) and [`CreateSubTaskDTO `]( https://github.com/doug-martin/nestjs-query/blob/master/examples/typeorm/src/sub-task/dto/subtask-input.dto.ts )

**Comment by SirMishaa** [comment]
What a pain. 

All relationships will be duplicated. This should be done automatically, I have already added above the class annotations.

I'm really starting to have doubts about the possibility of doing GraphQL properly on Nest.

**Comment by SirMishaa** [comment]
Thank you a lot, this is working well! 

But for this case of relation, how I'm supposed to work with it? Could you show me an example of how work with ``oneToMany`` and ``manyToMany`` relation ? Your example helped me a lot!  
```ts
  @ManyToMany(() => ProductCategory)
  @JoinTable({ name: 'product_category_item' })
  productCategories!: Array<ProductCategory>;
  
  @OneToMany(() => ProductImage, (productImage) => productImage.product)
  images!: Array<ProductImage>;
```

**Comment by doug-martin** [comment]
@SirMishaa there are a couple of ways to manage `many` relationships.

In the case of a `oneToMany`:
* You can create your relation entities using the pattern described above, the examples do this for  the `TodoItem->SubTask` relationship by exposing the `todoItemId` on the `CreateSubTaskDTO`. 
* If you want to add relationships using existing entities you can use the `add{PluralRelationName}To{DTOName}` mutation (e.g. `addSubTasksToTodoItem`)
* If you want to remove relationships using existing entities you can use the `remove{PluralRelationName}From{DTOName}` mutation (e.g. `removeSubTasksFromTodoItem`). In the case that your `manyToOne` relation has a non-nullable foreign key I would recommend using the `deleteOne{RelationName}` (e.g. `deleteOneSubTask`). 

For `manyToMany` relations you would typically manage the creates separately, so you could create your `Product` and `ProductCategories` and then use the `add`, `remove` methods. There is also a new mutation that was just added in`v0.26.0` `set{PluralRelationName}On{DTOName}` (e.g. `setProductCategoriesOnProduct`) to do a full replace of the relationships, which handles all the add/remove logic for you.

**Comment by SirMishaa** [comment]
Thanks for the explanations.
