### ISSUE TITLE
Allow declaration of custom ID scalar type

### ISSUE THREAD

**Issue by hrmcdonald** [doug-martin/nestjs-query#1058]
**Is your feature request related to a problem? Please describe.**

We would like to be able to specify a custom "ID" scalar type other than the default GraphQL `ID` scalar type. The default CRUD input types `nestjs-query` generates are fine other than the `ID` field automatically placed on a few types. This would prevent us from the mess of having to declare or generate custom input types for few different operations.

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?

yes!

**Describe the solution you'd like**

The default input type class factories already accept inputs. It should be relatively easy to pass an ID type from the resolver options to these factories.

I believe this would really only affect the generation of:

- `DeleteOneInputType`
- `UpdateOneInputType`
- `RelationInputType`
- `RelationsInputType`
- `FindOneArgsType`

**Describe alternatives you've considered**

I've built out an pipe that inspects value classes and uses the NestJS `TypeMetadataStorage` information on `InputType` values to determine when an argument or any of its child properties are `ID` types. I can then serialize and deserialize these properties before they hit any handlers. The problem with this is that besides the obvious hacky-ness of this solution, it's quite inefficient.

**Additional context**

I'll investigate what it would take to create a PR for this feature myself soon if you think this is something you'd be willing to include in the library, but I wanted to get a ticket up first.

---

btw - This is such an amazingly well made library. I'd love to contribute monetarily to its continued development if you ever enabled something like that!

**Comment by doug-martin** [comment]
@hrmcdonald thank you for submitting an enhacement request!  

This makes sense to me, I'm curious (if you can share) what is your ID scalar type? I like trying to keep everything type safe and currently the services all expect `string | number` for ids.

**Comment by hrmcdonald** [comment]
There are actually two variants I am interested in implementing, one that simply maps strings from the client to numbers on the API. I implemented a variant of the `nestjs-query` query service interface for [objection.js](https://vincit.github.io/objection.js/) because it is our ORM of choice (we're potentially open to considering contributing this to the main repo if you are interested). Given that a lot of projects simply use auto incrementing ids, having this scalar would help us remain type safe (even though most DBs do the type conversion for this basic scenario anyways, it can make things like testing more straight forward).

An iteration of that basic scalar I am interested in trying out however is one that uses something like a [feistel cipher](https://en.wikipedia.org/wiki/Feistel_cipher) to obfuscate auto-incrementing ids for added security so they cannot be scraped or guessed from the client in certain circumstance where that matters.

**Comment by ishwinder** [comment]
+1 to feature request. We also serialize the ids as strings in our responses. Right now we have to override the find by id resolver since the framework doesn't give us the flexibility to override `FindOneArgsType` to accept the id as scalar which we can serialize/deserialize as per our logic.

**Comment by ishwinder** [comment]
@hrmcdonald do you mind sharing the interceptor if its not too much proprietary code ?

**Comment by hrmcdonald** [comment]
Sure thing, I'm hoping to set aside some time to put together a PR for this feature within the next couple of weeks.

As for a scalar for that purpose, I have nothing fully tested yet but was playing around with something like I described above that seemed to work well. Although I'd need to look deeper into the performance implications of the [feistel-cipher](https://github.com/cyrildever/feistel-cipher) library and if that is a solution we would go with for this or not. You'd probably want to consider "salting" things in a more secure way too.
```
import { Scalar, CustomScalar } from '@nestjs/graphql';
import { Kind, ValueNode } from 'graphql';
import { Cipher } from 'feistel-cipher';
import * as nanomemoize from 'nano-memoize';

@Scalar('EID')
export class EID implements CustomScalar<string, number> {
  description = 'Alternative ID scalar that helps anonymize auto-incrementing DB IDs';
  cipher = new Cipher('some-private-key-here', 4); // would be populated via secret env var
  salt = 'some-other-private-key-here';

  parseValue(value: string): number {
    return this.deserialize(value);
  }

  parseLiteral(ast: ValueNode): number {
    if (ast.kind === Kind.STRING) {
      return this.deserialize(ast.value);
    }
    return null;
  }

  /** memoized serialize method that encrypts and obfuscates the id */
  serialize = nanomemoize((value: number): string => {
    return this.cipher
      .encrypt(`${this.salt}${value}`)
      .toString('base64');
  });

  /** memoized deserialize method that decrypts the id */
  private deserialize = nanomemoize((value: string): number => {
    const decryptedValue = this.cipher.decrypt(Buffer.from(value, 'base64'));
    const unsaltedValue = decryptedValue.slice(this.salt.length);
    try {
      return parseInt(unsaltedValue, 10);
    } catch(e) {
      return unsaltedValue;
    }
  })
}
```

**Comment by ishwinder** [comment]
ah .. scalar yeah, I do have a scalar for id as well going, I thought you had a pipe to intercept value classes and inspects the information on InputType values to determine when an argument or any of its child properties are ID types and serialize/deserialize them before handler is it.

**Comment by hrmcdonald** [comment]
> ah .. scalar yeah, I do have a scalar for id as well going, I thought you had a pipe to intercept value classes and inspects the information on InputType values to determine when an argument or any of its child properties are ID types and serialize/deserialize them before handler is it.

What a coincidence, I just reread your comment and realized I misunderstood before. I just updated my comment above with what you were looking for!

**Comment by doug-martin** [comment]
@hrmcdonald @ishwinder I realized I never went back and marked this issue as in progress (sorry about that). I hope to have the PR out later today or tomorrow. 

To keep the number of potential ID type mismatches and option passing down to a minimum I added a new `IDField` decorator that will replace the usage of `FilterableField` when you have a custom ID type you want to use. 

```ts
import { FilterableField, IDField } from '@nestjs-query/query-graphql';
import { ObjectType, GraphQLISODateTime } from '@nestjs/graphql';
import { CustomIDScalar } from '../../common/custom-id.scalar';

@ObjectType('TodoItem')
export class TodoItemDTO {
  @IDField(() => CustomIDScalar)
  id!: string;

  @FilterableField()
  title!: string;

  @FilterableField({ nullable: true })
  description?: string;

  @FilterableField()
  completed!: boolean;

  @FilterableField(() => GraphQLISODateTime, { filterOnly: true })
  created!: Date;

  @FilterableField(() => GraphQLISODateTime, { filterOnly: true })
  updated!: Date;
}

```

Just finishing up the examples and docs.

**Comment by doug-martin** [comment]
With `v0.27.0` you can now use a custom `graphql` scalar type for `id` fields. This release addresses this by adding a new `@IDField` decorator. 

For example, assume you have the following `CustomIDScalar` that obfuscates the id by `base64` encoding it. 

```ts
import { Scalar, CustomScalar } from '@nestjs/graphql';
import { Kind, ValueNode } from 'graphql';

@Scalar('CustomID')
export class CustomIDScalar implements CustomScalar<string, number> {
  description = 'ID custom scalar type';

  private idPrefix = 'id:';

  parseValue(value: string): number {
    // parse a `base64` encoded id from the client when provided as a variable
    return parseInt(Buffer.from(value, 'base64').toString('utf8').replace(this.idPrefix, ''), 10);
  }

  serialize(value: number): string {
    // serialize a number into the base64 representation
    return Buffer.from(`${this.idPrefix}${value}`, 'utf8').toString('base64');
  }

  parseLiteral(ast: ValueNode): number | null {
    // parse a `base64` encoded id from the client when hardcoded into the query
    if (ast.kind === Kind.STRING) {
      return this.parseValue(ast.value);
    }
    return null;
  }
}

```

You can now specify the custom `id` type for all `query` and `mutation` endpoints by using the `@IDField` decorator.

```ts
import { FilterableField, IDField } from '@nestjs-query/query-graphql';
import { ObjectType, GraphQLISODateTime } from '@nestjs/graphql';
import { CustomIDScalar } from '../../common/custom-id.scalar';

@ObjectType('TodoItem')
export class TodoItemDTO {
  @IDField(() => CustomIDScalar)
  id!: string;

  @FilterableField()
  title!: string;

  @FilterableField({ nullable: true })
  description?: string;

  @FilterableField()
  completed!: boolean;

  @FilterableField(() => GraphQLISODateTime, { filterOnly: true })
  created!: Date;

  @FilterableField(() => GraphQLISODateTime, { filterOnly: true })
  updated!: Date;
}
```
