### ISSUE TITLE
Computed field based on relation

### ISSUE THREAD

**Issue by Flusinerd** [doug-martin/nestjs-query#1067]
Hello,
I have the following issue:

I have a entity of type ``Project`` that contains ``MilestoneInstances`` that have multiple ``Tasks`` assigned to them.

A ``Task`` can be marked as ``finished`` by a field on ``Task`` and a ``MilestoneInstance`` is considered complete once all ``Tasks`` are complete. 

So I want to be able to have a virtual relation ``completedMilestones`` on ``Project`` that contain a subset of all of the projects ``MilestoneInstances`` that have all ``Tasks`` marked as compelted.

How would I go about implementing such a functionality?

**Comment by doug-martin** [comment]
@Flusinerd take a look at, each example is different based on the functionality needed. 

* https://doug-martin.github.io/nestjs-query/docs/graphql/resolvers#custom-endpoints
* https://doug-martin.github.io/nestjs-query/docs/graphql/authorization#using-authorizers-in-your-resolver
* https://doug-martin.github.io/nestjs-query/docs/graphql/hooks#example

Hope this helps!

**Comment by Flusinerd** [comment]
@doug-martin 
Ty this should help me getting it impletemented.
I am running into an issue now:

When trying to create the ``ConnectionType`` for the ``MilestoneInstanceDto`` I run in to the error:
```
Property 'ConnectionType' does not exist on type 'typeof MilestoneInstanceQuery'.ts(2339)
```

This is my types.ts
```ts
import { QueryArgsType } from "@nestjs-query/query-graphql";
import { ArgsType } from "@nestjs/graphql";
import { MilestoneInstanceDto } from "src/milestones/dto/milestone-instance/milestone-instance.dto";

@ArgsType()
export class MilestoneInstanceQuery extends QueryArgsType(MilestoneInstanceDto) {}
export const MilestoneInstanceConnection = MilestoneInstanceQuery.ConnectionType;
```

**Comment by doug-martin** [comment]
@Flusinerd that sounds like a version issue, what version of `nestjs-query` packages are you using?

**Comment by Flusinerd** [comment]
@doug-martin 
My versions are:
```
"@nestjs-query/core": "^0.23.0",
"@nestjs-query/query-graphql": "^0.23.0",
"@nestjs-query/query-typeorm": "^0.23.1",
```

**Comment by Flusinerd** [comment]
![image](https://user-images.githubusercontent.com/22977969/115056900-a781d280-9ee3-11eb-88b7-3a6b6def0884.png)

**Comment by Flusinerd** [comment]
![image](https://user-images.githubusercontent.com/22977969/115057209-0e06f080-9ee4-11eb-8279-9ddb4ab09db2.png)
Maybe this helps as well

**Comment by Flusinerd** [comment]
Indeed was an version issue. Installed v 0.26 and it works now 👍🏻 
Ty
