### ISSUE TITLE
How to create relation in mongoose

### ISSUE THREAD

**Issue by essarn** [doug-martin/nestjs-query#1178]
Hello, I have read the docs for relations with mongoose but I'm lost. I have created the relation between two DTOs but how do I actually link them together in GraphQL? I can create two individual entries but not figure out how to link them together. What mutations should I use and in what order?

Consider these two entries, `Story` and `Comment`. One of each can be created with `createOne(Story/Comment)` but when I try to use `addCommentsToStory` it returns `AddRelations not supported for virtual relation comments`. What am I doing wrong? 

Thanks!

**Comment by smolinari** [comment]
What does your code look like for the two entities? 

Also, this should be in discussions, as it isn't clear it is an issue. Transferring.

Scott
