### ISSUE TITLE
upgrade to support nest v8

### ISSUE THREAD

**Issue by Diluka** [doug-martin/nestjs-query#1219]
**Is your feature request related to a problem? Please describe.**

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Nightbr** [comment]
Hey, could be great to have some logs on what is not working on your end with Nest v8.

I tried to upgrade to Nest v8 on my project (using nestjs-query with TypeORM v0.28) and I get this error on bootstrap:

```
[Nest] 55633  - 2021-07-12 15:29:14   ERROR [ExceptionHandler] Nest cannot export a provider/module that is not a part of the currently processed module (NestjsQueryGraphQLModule). Please verify whether the exported NestjsQueryTypeOrmModule is available in this particular context.

Possible Solutions:
- Is NestjsQueryTypeOrmModule part of the relevant providers/imports within NestjsQueryGraphQLModule?

Error: Nest cannot export a provider/module that is not a part of the currently processed module (NestjsQueryGraphQLModule). Please verify whether the exported NestjsQueryTypeOrmModule is available in this particular context.

Possible Solutions:
- Is NestjsQueryTypeOrmModule part of the relevant providers/imports within NestjsQueryGraphQLModule?

```

**Comment by rhessus** [comment]
I have the same error.

**Comment by rosaan** [comment]
Upgraded to Nest V8 and facing the same issue:

```
Nest cannot export a provider/module that is not a part of the currently processed module (NestjsQueryGraphQLModule). Please verify whether the exported NestjsQueryTypeOrmModule is available in this particular context.

Possible Solutions:
- Is NestjsQueryTypeOrmModule part of the relevant providers/imports within NestjsQueryGraphQLModule?
```

**Comment by rodrigoSR** [comment]
I have the same error in Sequelize

 `[Nest] 10036  - 07/13/2021, 8:16:39 AM   ERROR [ExceptionHandler] Nest cannot export a provider/module that is not a part of the currently processed module (N
estjsQueryGraphQLModule). Please verify whether the exported NestjsQuerySequelizeModule is available in this particular context.

Possible Solutions:
- Is NestjsQuerySequelizeModule part of the relevant providers/imports within NestjsQueryGraphQLModule?`

**Comment by doug-martin** [comment]
I'm working on the update and will hopefully release shortly given there are no blocking issues!

**Comment by doug-martin** [comment]
Quick update, Nest v8 changed how dynamic modules work with importing/exporting. I'm working through ways of handling that, since its used extensively within each module.

**Comment by smolinari** [comment]
@doug-martin - Is it because of Nest complaining about not finding dependencies? If yes, export the module directly without the `forFeature`. 

Scott

**Comment by doug-martin** [comment]
Many of the problems were fixed over the past couple of days (in particular `v8.0.4`), I just published the latest version with updated deps!.
