### ISSUE TITLE
[Question] Is one-to-many relations nullable?

### ISSUE THREAD

**Issue by guanguangua** [doug-martin/nestjs-query#1224]
@doug-martin Hi dear doug, thanks you in advance for taking time looking at my question.

There is a one-to-many relation between driver and employments, defined with typeorm.
```ts
@Entity('drivers')
export class Driver {
  ...

  @OneToMany('Employment', 'driver', { nullable: true })
  employments?: Employment[];
}
```

And the relation is exposed to the graphql endpoint with the following segment

```ts
@FilterableUnPagedRelation('employments', () => Employment, {
  nullable: true
})
export class Driver {
  @FilterableField(() => ID)
  id: string;

  @FilterableField(() => ID)
  userID: string;

  ...
}
```

So my assumption is that if a driver has no employments, `null` will be returned. 

However, regardless of whether I set `nullable` to `true` or `false`, querying employment on driver will always return an empty array `[]` instead of null.

<table>
<tr>
<th> Query </th>
<th> Result </th>
</tr>
<tr>
<td>

```gql
query {
  driver(id: 1) {
    employments {
      id
    }
  }
}
```

</td>
<td>

```json
{
  "data": {
    "driver": {
      "employments": []
    }
  }
}
```

</td>
</tr>
</table>

But setting `nullable` will affect how `schema.gql` is generated. 

So my question is, how does nullable affects relations, and is it safe to assume that I don't ever need `nullable` for one-to-many, many-to-many relations? Since the result seems to always be an empty array?

**Comment by doug-martin** [comment]
Hi @guanguangua thanks for the question! When querying a many relation it will always return an array, as you see in your example if no relations are found the array will be empty.

**Comment by guanguangua** [comment]
> Hi @guanguangua thanks for the question! When querying a many relation it will always return an array, as you see in your example if no relations are found the array will be empty.

Thank you!
