### ISSUE TITLE
[enhancement] combine hooks into one class

### ISSUE THREAD

**Issue by onichandame** [doug-martin/nestjs-query#1290]
**Is your feature request related to a problem? Please describe.**
Now for every operation in `createOne`, `createMany`, `updateOne` and `updateMany`, an individual hook class has to be written. So at most 4 classes with similar logic are necessary.

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?

√

**Describe the solution you'd like**
I'd like to have all hooks defined in one class once and for all, like [typeorm subscriber](https://github.com/typeorm/typeorm/blob/master/docs/listeners-and-subscribers.md#what-is-a-subscriber)

**Describe alternatives you've considered**

**Additional context**

**Comment by smolinari** [comment]
> Now for every operation in createOne, createMany, updateOne and updateMany, an individual hook class has to be written.

Are you sure? Couldn't you give the same class to each hook implemented just from the `Hook` interface? 

Scott

**Comment by onichandame** [comment]
How? I just tried to implement a `Hook` and pass it to `BeforeUpdateOne`, it didn't pass tsc check as the argument type of the `run` function is incompatible with that of the `BeforeUpdateOneHook`.

@smolinari Could you show me a working example? I couldn't find anything about your approach either in the docs or on the internet.

**Comment by smolinari** [comment]
Ok. Nevermind. It doesn't work. 

Scott

**Comment by doug-martin** [comment]
@onichandame good question! You can combine hooks into a single class, check out https://github.com/doug-martin/nestjs-query/blob/master/examples/hooks/src/hooks.ts#L26 in that example we combine the UpdateOne/Many and CreateOne/Many into classes that can do both. Using that as a base you should be able combine all four into a single hook

Hope this helps!

**Comment by smolinari** [comment]
Buggers. How could I miss that. Thanks Doug!!!

Scott
