### ISSUE TITLE
support @nestjs/graphql v9

### ISSUE THREAD

**Issue by Diluka** [doug-martin/nestjs-query#1328]
**Describe the bug**
install `npm i @nestjs-query/query-graphql @nestjs/common @nestjs/graphql graphql graphql-subscriptions class-transformer class-validator dataloader` which is print on homepage using node16 with npm7 workspace

```log
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: api@0.0.1
npm ERR! Found: @nestjs/graphql@9.0.2
npm ERR! node_modules/@nestjs/graphql
npm ERR!   @nestjs/graphql@"^9.0.2" from api@0.0.1
npm ERR!   packages/api
npm ERR!     api@0.0.1
npm ERR!     node_modules/api
npm ERR!       workspace packages/api from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/graphql@"^8.0.0" from @nestjs-query/query-graphql@0.28.1
npm ERR! node_modules/@nestjs-query/query-graphql
npm ERR!   @nestjs-query/query-graphql@"*" from api@0.0.1
npm ERR!   packages/api
npm ERR!     api@0.0.1
npm ERR!     node_modules/api
npm ERR!       workspace packages/api from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/diluka/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/diluka/.npm/_logs/2021-09-02T09_12_06_538Z-debug.log
```

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

**To Reproduce**
1. `npm i @nestjs-query/query-graphql @nestjs/common @nestjs/graphql graphql graphql-subscriptions class-transformer class-validator dataloader -w api`
2. crash

**Expected behavior**
no error

**Screenshots**

**Desktop (please complete the following information):**
 - Node Version [e.g. 14.14.0] v16.8.0
 - Nestjs-query Version [e.g. v0.21.0]

**Additional context**

**Comment by doug-martin** [comment]
@Diluka in `v0.30.0` I upgraded to the latest @nestjs/graphql packages.
