### ISSUE TITLE
hasPreviousPage always return false

### ISSUE THREAD

**Issue by zerox12311** [doug-martin/nestjs-query#133]
I using paging with **first** and **after** to change my cursor in my graph query but I get **hasPreviousPage** always return false, I think it is a bug?

**Comment by zerox12311** [comment]
I have created a pull request, but I don't know what branch should created it. 
Please have a look of it.

**Comment by doug-martin** [comment]
Fixed an published `@nestjs-query/query-graphql` `v0.10.1`
