### ISSUE TITLE
Manually publish created{ObjectName} event from service

### ISSUE THREAD

**Issue by Flusinerd** [doug-martin/nestjs-query#1361]
Hello,
I have a service where I have the need to manually publish the created event for my DTO.

I have tried to inject the pubSub using

```ts
@InjectPubSub() readonly pubSub: PubSub
```

and then

```ts
const savedEntity = await this.db.save(...);
pubSub.publish('createdMessageNotification',  savedEntity)
```

But the subscribed clients do not get the event. (I tried with playground, which allows for the subscription, but does not get the published event)
How can I manually publish the created event?

I am using a automatically generated resolver, but also tried defining a basic CRUD resolver and injecting the resolver:

```ts
import { CRUDResolver, InjectPubSub } from '@nestjs-query/query-graphql';
import { Resolver } from '@nestjs/graphql';
import { PubSub } from 'graphql-subscriptions';
import { MessageNotification } from '../push/entities/MessageNotification.entity';
import { MessageNotificationDto } from './dto/message-notification.dto';
import { UpdateMessageNotificationDto } from './dto/update-message-notification.dto';
import { MessageNotificationRelationQueryService } from './services/message-notification-relation-query.service';

@Resolver(() => MessageNotification)
export class MessageNotificationResolver extends CRUDResolver(
  MessageNotificationDto,
  {
    UpdateDTOClass: UpdateMessageNotificationDto,
    create: { disabled: true },
    delete: { disabled: true },
    enableSubscriptions: true,
  }
) {
  constructor(
    readonly service: MessageNotificationRelationQueryService,
    @InjectPubSub() readonly pubSub: PubSub
  ) {
    super(service);
  }
}
```

And then calling the ``createOne()`` method of the resolver

Sincerely,
Jan

**Comment by doug-martin** [comment]
@Flusinerd it's hard to say without a full example, could you provide the subscription endpoint defined in your resolver?

**Comment by Flusinerd** [comment]
A way to inject the autogenerated resolver / getting the pubsub from the autogenerated resolver would work for me just fine
I dont need to override the default behaviour. I only need to be able to trigger the created event from somewhere other then the resolver / query-service

**Comment by doug-martin** [comment]
@Flusinerd I just tried this locally there are few things that you need to change to get his working, I think we can make this easier by exposing a few methods from the autogenerated resolves but to get you progressing forward you need to change your publish to this 

```
await this.pubsub.publish('createdMessageNotification-{}', { createdMessageNotification: savedEntity });
```

the triggerName published has an empty filter to support subscriptions with authorization filters, in the default case it is empty. The payload of the event should have the `createdMessageNotification` because the subscriptions look for a key on the payload that should be published out similar to https://docs.nestjs.com/graphql/subscriptions#publishing.

**Comment by Flusinerd** [comment]
Awesome ty, did you use the auto generated resolver, if so how did you inject it? What is the correct token?

Or did you just create one yourself and extend from that one, like I did?

**Comment by doug-martin** [comment]
No problem! 

I just created a basic nestjs/graphql resolver and injected the PubSub into the constructor, and because its the same instance that the autogenerated resolver is using the events are emitted as expected.

### Example

Create a new resolver, it doesn't need to extend crud resolver or anything (I didn't know nest allows you to have more than one resolver for a DTO for quite a while :) ) 

```ts
import { Mutation, Resolver } from '@nestjs/graphql';
import { TodoItemDTO } from './dto/todo-item.dto';
import { InjectPubSub } from '@nestjs-query/query-graphql';
import { PubSub } from 'graphql-subscriptions';

@Resolver(() => TodoItemDTO)
export class TodoItemResolver {
  constructor(@InjectPubSub() readonly pubsub: PubSub) {}

  // basic mutation that just creates a dummy todoItem and publishes an event
  @Mutation(() => TodoItemDTO)
  async publishTodoItemCreateEvent(): Promise<TodoItemDTO> {
    const todoItem = new TodoItemDTO();
    todoItem.id = -1;
    todoItem.title = 'Published Todo';
    todoItem.completed = false;
    todoItem.created = new Date();
    todoItem.updated = new Date();
    todoItem.description = 'A fake published todoItem';
    // publish the event
    await this.pubsub.publish('createdTodoItem-{}', { createdTodoItem: todoItem });
    return todoItem;
  }
}

```

Then register it in your module along side the autogenerated one

```ts
import { NestjsQueryGraphQLModule } from '@nestjs-query/query-graphql';
import { NestjsQueryTypeOrmModule } from '@nestjs-query/query-typeorm';
import { Module } from '@nestjs/common';
import { TodoItemInputDTO } from './dto/todo-item-input.dto';
import { TodoItemUpdateDTO } from './dto/todo-item-update.dto';
import { TodoItemDTO } from './dto/todo-item.dto';
import { TodoItemEntity } from './todo-item.entity';
import { TodoItemResolver } from './todo-item.resolver';

@Module({
  imports: [
    NestjsQueryGraphQLModule.forFeature({
      imports: [NestjsQueryTypeOrmModule.forFeature([TodoItemEntity])],
      resolvers: [
        {
          DTOClass: TodoItemDTO,
          EntityClass: TodoItemEntity,
          CreateDTOClass: TodoItemInputDTO,
          UpdateDTOClass: TodoItemUpdateDTO,
          enableSubscriptions: true,
        },
      ],
    }),
  ],
  // register like normal
  providers: [TodoItemResolver],
})
export class TodoItemModule {}

```

Hope this helps!

**Comment by Flusinerd** [comment]
Awesome ty, I managed to get it working using your example / explanation.

**Comment by emmalex6250** [comment]
@doug-martin I have tried to follow your suggestion unfortunately for me my subscribing clients are not getting the updates. I have to not am trying to do this from the a service rather than a resolver

**Comment by emmalex6250** [comment]
`try {
      const notification = Notification.create({
        playerId: challenge.player2Id,
        message: `${
          invitingPlayer.username
        } has invited you for a challenge on ${format(
          challenge.challengeDate,
          'dd-MM-yyyy H:mm',
        )} for ${challenge.stake} points`,
        type: NotificationType.PLAYER_INVITED_FOR_CHALLENGE,
      })
      const savedNotification = await Notification.save(notification)
      await this.pubsub.publish('createdNotification', {
        createdNotification: savedNotification,
      })
    } catch (e) {
      console.log(e)
    }`

**Comment by Flusinerd** [comment]
@emmalex6250 You are missing ``{}`` behind your event name.

Try
``createdNotification-{}``

**Comment by emmalex6250** [comment]
@Flusinerd I added `{}` but still cannot get updates to the subscribing clients 

     const savedNotification = await Notification.save(notification)
      await this.pubsub.publish('createdNotification-{}', {
        createdNotification: savedNotification,
     })

**Comment by emmalex6250** [comment]
the way I am trying to set a manual publish is from an interceptor, so at the end of a particular graphql operation I call the interceptor which creates the notification and is supposed to publish the new notification to the subscribing clients. I can create the notification but I can not publish it to clients. I was wondering does it work only when you call it from the resolver or is it supposed to work when called from any part of the application
