### ISSUE TITLE
[Question] Custom Service not reflected in GraphQL Docs

### ISSUE THREAD

**Issue by ThianHooi** [doug-martin/nestjs-query#1499]
I have been following the examples in the doc. I would like to add our custom services following this [doc](https://doug-martin.github.io/nestjs-query/docs/persistence/typeorm/custom-service), but the query is not reflected in the GraphQL playground. 

I am sure every line of code are the same as in the documentation. Are there any parts that I am missing or are there any missing parts in the doc?

**Comment by smolinari** [comment]
@ThianHooi - Services have absolutely nothing to do with GraphQL. Resolvers do. 

Scott

**Comment by ThianHooi** [comment]
@smolinari Thanks for response. Does this mean that I will have to add own resolver to add new endpoint?

**Comment by smolinari** [comment]
@ThianHooi - Depends on what you are looking to do, but yes. You need to create resolvers, object types and arg types for them to be generated into GraphQL schema. 

Scott
