### ISSUE TITLE
Support for TypeORM 0.3

### ISSUE THREAD

**Issue by abidon** [doug-martin/nestjs-query#1549]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today we used [patch-package](https://github.com/ds300/patch-package) to patch `@nestjs-query/query-typeorm@0.30.0` for the project we are working on. This patch made our codebase work with TypeORM 0.3.

---

Apparently, with TypeORM 0.3, `this.repo.manager.getRepository(relationMeta.type).target` return a `string` instead of the entity `class` in some cases.

```
// (1) in TodoEntity.ts
@ManyToOne(() => ProjectEntity)
project: ProjectEntity;

// (2) in ProjectEntity.ts
@OneToMany('TodoEntity', (todo) => todo.project
todos: TodoEntity[]
```

1. When specifying a `typeFunction`, `repository.target` equals the `ProjectEntity` class
2. ⚠️ When specifying a `string`, `repository.target` is the `'TodoEntity'` string, not class

This behaviour was introduced in TypeORM 0.3 and breaks nestjs-query, while TypeORM 0.2 always returned the entity class (at least in our use cases).

---

Here is the diff that solved our problem:

```diff
diff --git a/node_modules/@nestjs-query/query-typeorm/dist/src/services/relation-query.service.js b/node_modules/@nestjs-query/query-typeorm/dist/src/services/relation-query.service.js
index 0d46f16..8d06fee 100644
--- a/node_modules/@nestjs-query/query-typeorm/dist/src/services/relation-query.service.js
+++ b/node_modules/@nestjs-query/query-typeorm/dist/src/services/relation-query.service.js
@@ -245,7 +245,7 @@ class RelationQueryService {
     getRelationEntity(relationName) {
         const relationMeta = this.getRelationMeta(relationName);
         if (typeof relationMeta.type === 'string') {
-            return this.repo.manager.getRepository(relationMeta.type).target;
+            return this.repo.manager.connection.entityMetadatas.find(em => em.targetName == relationMeta.type).target;
         }
         return relationMeta.type;
     }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by TriPSs** [comment]
TypeORM v3 support is now released in the alpha version of my [fork](https://github.com/TriPSs/nestjs-query/pull/26) together with all the fixes from [here](https://github.com/doug-martin/nestjs-query/issues/1538#issuecomment-1142113415)

**Comment by henry-huynh-3508** [comment]
> TypeORM v3 support is now released in the alpha version of my [fork](https://github.com/TriPSs/nestjs-query/pull/26) together with all the fixes from [here](https://github.com/doug-martin/nestjs-query/issues/1538#issuecomment-1142113415)

Thanks TriPSs for keeping fixing the project bugs. The project owner should have transferred things over if he no longer continues to maintain this project, what a shame that it's a good project.

**Comment by dzcpy** [comment]
Any updates?
