### ISSUE TITLE
It's support dataloader?

### ISSUE THREAD

**Issue by zerox12311** [doug-martin/nestjs-query#17]
It is a really amazing nestjs graphql library!!
I tried this library for example code, and i found some problem.
I used **many Relations** in resolver, it work fine!, but will cause n+1 problem.
I think can add a batch option to use any batch function to resolve it.

**Comment by doug-martin** [comment]
Im looking into this now.

**Comment by doug-martin** [comment]
in `v0.3.0` dataloader support has been added.
