### ISSUE TITLE
[Possibility] Subscription feature possibility

### ISSUE THREAD

**Issue by ridyio** [doug-martin/nestjs-query#171]
I have been wondering if it would be possible/planned to include subscription with this library. Subscription can create neat user experiences but creating them in manual way is cumbersome to do. Generally subscriptions can be useful for a few types of listeners. Can't they be implemented into library so they would get called upon mutations?
Sorry if my question has lack of understanding on how library works. New to GraphQL :)

**Comment by doug-martin** [comment]
@ridyio thank you for the question. 

TBH I havent looked into subscriptions in nestjs-graphql too much yet. I have been more focused on stabilizing the library and working towards a `v1`

Feel free to research and propose a plan!

**Comment by johannesschobel** [comment]
Dear @doug-martin ,
wow, glad to hear about the `v1` information! that is awesome news.. Do you have an estimated time plan for this? Just wondering!

**Comment by doug-martin** [comment]
@ridyio I've added subscriptions to CRUD operations in `v0.12.0`. You can check out the docs at https://doug-martin.github.io/nestjs-query/docs/graphql/subscriptions

Feel free to provide any feedback.

Thanks!

**Comment by johannesschobel** [comment]
wooooooooooooha.. that is very (!) nice.. love it.. i will try to implement it in my application during the following week..

**Comment by ridyio** [comment]
@doug-martin Thanks a lot, It is a very nice feature I didn't looked deeply into API yet but I will stay awake tonight doing so😜
I think this feature is not available now but count subscriptions could be a nice feature to have (mind blowing if filtered too🙈), I understand filtered might not even be possible. I remember rethinkDB doing same job on database level and it was great but as there was no nice interface for it like GraphQL i couldn't bring it to production table.
Anyway that was a great job and thank you for it.
