### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by kodeine** [doug-martin/nestjs-query#207]
is it possible to add [events](https://github.com/javascript-dragons/nest-event)?

**Comment by doug-martin** [comment]
@kodeine you can currently add the decorators from that library to the resolver, however I think this probably belongs on the QueryService. 

Ill look into adding this in an upcoming release.

**Comment by doug-martin** [comment]
@kodeine I recently added subscription support using the graphql-subscriptions library. I know its not the library you linked to but it looks like it will do the same thing using subscriptions.

**Comment by kodeine** [comment]
Awesome, thank you!
