### ISSUE TITLE
[Bug]: GetById(NULL)

### ISSUE THREAD

**Issue by johannesschobel** [doug-martin/nestjs-query#212]
Dear @doug-martin ,

i recently noticed a bug (at least i call it a bug) in the `typeorm` package with the `DatabaseService / AssemblerService.getById()` and `.findById()` methods.

Both methods return **the first entity in the table** if you call them with `null` or `undefined` as parameter.

For example:
```ts
const user = this.userAssemblerService.getById(null);
```
returns the first user from the table - which is clearly wrong ;)
What do you think, we should handle this? I can provide a PR, if you like

**UPDATE**
I just noticed, that there are no test-cases for this scenario. However, in your repository, the IDE correctly mentions the latter as error (if i pass `null` ). Are there any specific configurations you have enabled?

**Comment by johannesschobel** [comment]
ok, i think, this is because of the `strict: true` flag in your `tsconfig`. However, mine does not use the `strict: true`, and therefore i can pass `null / undefined` as well. 

Shall we prevent this behaviour via an additional check in both functions?

**Comment by doug-martin** [comment]
I'm hesitant to change this because
1. The type signature does not allow for null and I dont think it makes sense to check for null when the method doesnt accept that value
2. The TS compiler can help prevent errors like this. 

I haven't used typescript without `strict:true`, are you able pass in null for other methods also? Is there a reason you do not have strict enabled?

**Comment by johannesschobel** [comment]
Dear @doug-martin ,
thank you for your answer. I think, `strict` is not enabled by default, therefore, i don't have it enabled ;) I can pass `null` and `undefined` as function parameter, because with `strict: false` those 2 values are in every type domain (for `string`, `number`, `objects`, ...)..

All the best
