### ISSUE TITLE
[FR] support filterable enum fields

### ISSUE THREAD

**Issue by Diluka** [doug-martin/nestjs-query#224]
currently raise errors when fileds are enum typed

**Comment by Diluka** [comment]
https://github.com/doug-martin/nestjs-query/blob/fe181ae67a10599974a58246cbababbb07ff32e5/packages/query-graphql/src/types/query/field-comparison/field-comparison.factory.ts#L26-L27

enum is not class, so it doesn't have `name` property

**Comment by doug-martin** [comment]
Hi @Diluka thank you for the bug report! This has been fixed and release under `v0.13.2`

**Comment by johannesschobel** [comment]
Dear @doug-martin , i just stumbled upon the same issue that @Diluka described. And **once again** i am completely surprised by your support! That is so awesome! :+1:
