### ISSUE TITLE
[Feature Request] Support for without paging

### ISSUE THREAD

**Issue by zerox12311** [doug-martin/nestjs-query#251]
Sometime I know the data is not need to paging, but the library is default to paging and no option to close it.
Have possible to supply a option to close it?

**Comment by rglepper** [comment]
@doug-martin The main use case for having a way to avoid the pagination would be something like the TodoItems that you use for the example. If you implement a client, and create a new todoItem, on the client, it would normally be added to a list of todos, but if the list is paginated there's an unnecessary overhead to figure out where the newly created item should go etc. In this kind of application it's very unlikely that the pagination is needed all the time eg. Asana or Jira where only the search is paginated

On the [GraphQL Pagination docs](https://graphql.org/learn/pagination/) there's an example at the bottom of a helper to bypass the pagination should you want to:
> Also, try replacing the edges field with the helper friends field on the connection, which lets you get directly to the list of friends without the additional edge layer of indirection, when that's appropriate for clients.

I think this is a very convenient implementation as it adds loads of flexibility to the findAll query.

Cheers

**Comment by doug-martin** [comment]
Starting to think about his more...would you expect the query functionality to work the same way, with filters, sorting, and a modified version of the paging option? Or remove the paging option all together?

**Comment by zerox12311** [comment]
I think it should be keep filters and sorting.
On the frontend side, if it can filter data at one time is more better then filter by frontend side.
For example:
Sometimes save selection option in database, and need to query it only in one time can fetch all data, if have some condition to filter in frontend, it will be increase more cost.
```graphql
{
  option1(filter: {FILTER_CONDITION}) {
      id
      optionLabel
  }
  
  option2 {
      id
      optionLabel
  }
}
```

**Comment by rglepper** [comment]
@doug-martin I think that having the filters and sorting would be nice to have but not required. From my point of view the main feature would be to be able to make a query that returns a response without pages, edges and nodes/cursors

**Comment by doug-martin** [comment]
Hi Everyone. I've done an initial implementation of this which will allow you to bypass the connection implementation entirely in `v0.13.0`

In short I added a new `pagingStrategy` option which you can now set to `OFFSET` so you can still query/sort/page but without the overhead of relay connections, that in addition to `defaultResultSize` option you should be able to ignore paging entirely.

Check out these docs for more information on how to use with a resolver or your relations. 
* https://doug-martin.github.io/nestjs-query/docs/graphql/resolvers#paging-strategy
* https://doug-martin.github.io/nestjs-query/docs/graphql/relations#many-relation
* https://doug-martin.github.io/nestjs-query/docs/graphql/relations#manual-relation-definition

**Comment by doug-martin** [comment]
I hope to add a `NONE` `pagingStrategy` in the future but that turned out to be a little more invasive than this change.

**Comment by doug-martin** [comment]
@rglepper @zerox12311 A new version (`v0.14.0`) has been published that added a new `PagingStrategies.NONE` option to turn off paging all together. 

Have a great weekend!
