### ISSUE TITLE
Can't create Resolver class

### ISSUE THREAD

**Issue by izundo-viennv** [doug-martin/nestjs-query#26]
I can't create Resolver class. Please see image below: 
![image](https://user-images.githubusercontent.com/29116432/75092410-c9b2e580-55a9-11ea-9f32-94b6bf98ec24.png)

![image](https://user-images.githubusercontent.com/29116432/75092430-fcf57480-55a9-11ea-83f5-2dc884f8b14b.png)

![image](https://user-images.githubusercontent.com/29116432/75092440-14ccf880-55aa-11ea-82f7-fbddde4dbd61.png)

![image](https://user-images.githubusercontent.com/29116432/75092453-3332f400-55aa-11ea-9252-606a902f86ec.png)

**Comment by doug-martin** [comment]
I see your missing quite a few peer dependencies, but it may be a version issue.

What version of query-typeorm are you using?

**Comment by doug-martin** [comment]
I was able to reproduce locally by setting by having this dependency combination.
```
"@nestjs-query/core": "^0.2.1",
"@nestjs-query/query-graphql": "^0.3.0",
"@nestjs-query/query-typeorm": "^0.2.0",
```
To fix you should upgrade `core` and `query-typeorm` to 

```
"@nestjs-query/core": "^0.3.0",
"@nestjs-query/query-graphql": "^0.3.0",
"@nestjs-query/query-typeorm": "^0.3.1",
```

**Comment by izundo-viennv** [comment]
@doug-martin Thank you, You're right.
