### ISSUE TITLE
FilterableField with scalar type from graphql-iso-date don't support

### ISSUE THREAD

**Issue by Diluka** [doug-martin/nestjs-query#299]
https://www.npmjs.com/package/graphql-iso-date

Unable to create filter comparison for "Date".

**Comment by doug-martin** [comment]
I haven't tried it, but is this different from `GraphQLISODateTime` provided by nestjs/graphql? 

At a cursory glance It looks like this scalar will supports date formatting `yyyy-MM-dd` where the nestjs/graphql will do the full ISO date time format, is that correct?

**Comment by Diluka** [comment]
I use this lib to introduce `YYYY-MM-DD` format to avoid timezone problems

**Comment by doug-martin** [comment]
@Diluka fix published! `v0.14.1`
