### ISSUE TITLE
module has no exported member 'InjectPubSub'

### ISSUE THREAD

**Issue by innomal** [doug-martin/nestjs-query#310]
Hello,
I was trying to implement subscription in latest version of library but i found at least one error in documentation:
This is my module:
```
@Module({
  imports: [NestjsQueryTypeOrmModule.forFeature([User])],
  controllers: [UserController],
  providers: [UserService, UserResolver],
  exports: [UserService],
})
export class UserModule {}
```
Service:
```
@Injectable()
export class UserService extends TypeOrmQueryService<User> {
  constructor(@InjectRepository(User) private userRepo: Repository<User>) {
    super(userRepo);
  }
}
```
Resolver:
```
@Resolver()
export class UserResolver extends CRUDResolver(UserDTO, { enableSubscriptions: true }) {
    constructor(
        service: UserService,
        @InjectPubSub() readonly pubSub: PubSub
    ) {
        super(service);
    }
}
```
Running this throws error:
```
src/user/user.resolver.ts:3:24 - error TS2305: Module '"../../node_modules/@nestjs-query/query-graphql/dist/src"' has no exported member 'InjectPubSub'.

3 import { CRUDResolver, InjectPubSub } from '@nestjs-query/query-graphql';
```
If i remove the pubsub injection it compiles but throws follwing error when i want to subscribe from graphql Playground.
`Unable to subscribe to createdUser`
Not sure later error is due to pubsub not being injected into resolver constructor, just told what happens if i don't inject it.

Thanks,

**Comment by doug-martin** [comment]
@innomal thank you for the bug report! I have published a fix under `v0.14.3`.

Thanks again!

**Comment by doug-martin** [comment]
@innomal you will also need to import the `NestjsQueryGraphQLModule` inorder to get the pubsub provider.

```ts
@Module({
  imports: [
    NestjsQueryTypeOrmModule.forFeature([User]),
    NestjsQueryGraphQLModule.forFeature({ imports: [], resolvers: [] })
  ],
  controllers: [UserController],
  providers: [UserService, UserResolver],
  exports: [UserService],
})
```

I'll work on making this clearer in the docs, and update the graphql module to not require imports or resolvers when just using it for the pub sub feature.

**Comment by innomal** [comment]
Thanks a lot! I just tested and subscription feature works like a charm.
