### ISSUE TITLE
Suggestion: Improve feedback for misuse of "@Resolver" Decorator (relations always null)

### ISSUE THREAD

**Issue by Gonozal** [doug-martin/nestjs-query#311]
First of: Awesome Library.

Issue: When Using the `@Resolver()` Decorator from `@nestjs/graphql` without a `typeFunc` argument, the resolver works (good I guess?). However, it won't resolve any relations and always return `null` instead.

Example of the type of misuse:

```typescript
@Resolver()  // <-- missing return-type function
export class UserGroupResolver extends CRUDResolver(UserGroup, {
  relations: {
    many: {
      users: { DTO: User }
    }
  }
}) {
constructor(
    @InjectQueryService(UserGroup)
    readonly service: QueryService<UserGroup>
  ) {
    super(service);
  }
}
```

All of the queries and mutations generated by `CRUDResolver` work (`getUserGroups` etc.). However, trying to access `users` on the returned `userGroup` always returns null and no queries to fetch users are made. This applies to Both the manual `relations` definition inside the Resolver-Options and to the decorator-based Relation/Connection definition in the DTOs.

This is fixed by proper use of the `@Resolver` Decorator:

```typescript
@Resolver(() => UserGroup) // <-- correct usage
export class UserGroupResolver extends CRUDResolver(UserGroup, {
  relations: {
    many: {
      users: { DTO: User }
    }
  }
}) {
constructor(
    @InjectQueryService(UserGroup)
    readonly service: QueryService<UserGroup>
  ) {
    super(service);
  }
}
```

Would it be possible to throw runtime errors when encountering such a case?
If not, at least this issue might help another poor soul to debug and fix "null" responses in relations faster than me.

**Comment by doug-martin** [comment]
@Gonozal very good point! I've actually done this before too, the problem is `Resolver` comes from `@nestjs/graphql` so there is not a way for `@nestjs-query` to identify this kind of mistake.

I think having this issue here and calling it out in the docs. would help.

I'll update the docs with a note about this.

**Comment by doug-martin** [comment]
Added docs!
