### ISSUE TITLE
[FR]make connection compatible with cursor and page based pagination

### ISSUE THREAD

**Issue by Diluka** [doug-martin/nestjs-query#327]
the best practice describe https://graphql.org/learn/pagination/

- using `first` and `offset` for page based pagination
- using `first` and `after` for cursor based top-down pagination
- using `last` and `before` for cursor based bottom-up pagination

returning results share the same connection model

#43

**Comment by Diluka** [comment]
If someone eagerly want to add this feature immediately. Let's do some hack.

This is working on `v0.21.2`
https://gist.github.com/Diluka/8b87158fdf55808e44b1ed3c513f2eea

**Comment by doug-martin** [comment]
I won't be adding `offset` to cursor based paging at this time.  I'll keep an eye on this and if it becomes a more frequently requested feature I'll reconsider.
