### ISSUE TITLE
[Enhancement] count query

### ISSUE THREAD

**Issue by innomal** [doug-martin/nestjs-query#355]
Hello Martin,
I can see there has been some discussion about `totalCount` in queries and you encouraged on creating new issue and explaining use case, so here it goes :)
Default cursor mode is good for unlimited pagination but in dashboard type of application most of tables work on offset based and they require `count` to paginate data correctly.
As you said count query can be expensive so running it on each query might not be a good idea and is not required. For example during pagination it is pointless to run query again (which i assume happens in cursor mode with `enabledTotalCount`). A separate query that would be called manually only when filter changes could work better.
To that end i think if there was a query for count it could be helpful. I see that there is a `count` method on service but it is not in resolver base functions.
Right now i use below function in each resolver class:
```
@Query(returns => Int)
async getUserCount(@Args('filter', {type: () => FilterType(UserDTO)}) filter: Filter<User>): Promise<number> {
    return this.service.count(filter);
}
```

Moreover a subscription to cover this scenario on count changes can be useful, Current subscriptions filters don't cover scenarios for this use case very well.

Thanks again

**Comment by doug-martin** [comment]
@innomal good point lets track this under #345 which I thin will be more flexible. Thank your for submitting an issue!
