### ISSUE TITLE
[ERROR] v0.16.0 - relation query service

### ISSUE THREAD

**Issue by GustavoLofrano** [doug-martin/nestjs-query#363]
![image](https://user-images.githubusercontent.com/36713355/86805131-fabe1f00-c04d-11ea-84e3-15a54c525f2b.png)

Remove "/src" from import { Filter } from '@nestjs-query/core/src';

node_modules/@nestjs-query/query-typeorm/dist/src/services/relation-query.service.d.ts

I remove it manually, the code will work

**Comment by doug-martin** [comment]
Thank you for submitting, I'm unsure how the tests passed for this. I'll look into that separately. I'll push up a patched version asap.

**Comment by doug-martin** [comment]
@GustavoLofrano fix published.
