### ISSUE TITLE
[Feature Request] Add query depth limit

### ISSUE THREAD

**Issue by zerox12311** [doug-martin/nestjs-query#365]
Sometime I hope the query depth not too much.
I think can add a query depth limit in each resolvers?

**Comment by doug-martin** [comment]
@zerox12311 For the most part `nestjs-query` already supported this, but I did add the ability to specify complexity on relations in `v0.17.1`. 

Using field and relation complexity you should be able to achieve this. Check out the [nest docs on complexity](https://docs.nestjs.com/graphql/complexity)
