### ISSUE TITLE
__typename in aggregate queries

### ISSUE THREAD

**Issue by olehs** [doug-martin/nestjs-query#394]
Hi.
apollo-client adds `__typename` to every query resulting in queries like this
```graphql
userAggregate {
  count {
    id
    __typename
  }
}
```
This leads to wrapping this extra field in aggregate function in final SQL, created by nestjs-query
```SQL
SELECT COUNT("UserEntity"."id") AS "COUNT_id", COUNT(UserEntity.__typename) AS "COUNT___typename" FROM "user_entity" "UserEntity"
```
I guess `__typename` needs special processing for this case, doesn't it?

**Comment by doug-martin** [comment]
Fixed in `v0.17.5`

Thank you for reporting!
