### ISSUE TITLE
Add ability to limit filter comparisons

### ISSUE THREAD

**Issue by ikottman** [doug-martin/nestjs-query#397]
Currently all [possible comparisons](https://doug-martin.github.io/nestjs-query/docs/concepts/queries#common-comparisons) are always included when filtering. I would like to configure what comparisons are allowed for a filterable field/relation. This would simplify my API to only include a subset of comparisons I want to support.

Something like this:
```javascript
import { FilterableField } from '@nestjs-query/query-graphql';
import { ObjectType } from '@nestjs/graphql';

@ObjectType('User')
export class User {
  @FilterableField({ allowComparison: ['eq', 'like'] })
  name!: string;
}
```

to restrict filtering name to only `eq` and `like`.

**Comment by doug-martin** [comment]
@ikottman this feature is now available in `v0.17.8`

You can read more about it [here](https://doug-martin.github.io/nestjs-query/docs/graphql/dtos#filterablefield)

Thanks for the feature request!
