### ISSUE TITLE
Make a filter required

### ISSUE THREAD

**Issue by ikottman** [doug-martin/nestjs-query#398]
I'd like a way to configure a filterable field/relation to be required. This would let my schema enforce a filter is specified with a value when querying.

Something like:
```javascript
import { FilterableField } from '@nestjs-query/query-graphql';
import { ObjectType } from '@nestjs/graphql';

@ObjectType('User')
export class User {
  @FilterableField({ required: true })
  authServiceUuid!: string;
}

```

**Comment by doug-martin** [comment]
@ikottman this is release under `v0.17.9`. You can checkout the docs [here](https://doug-martin.github.io/nestjs-query/docs/graphql/dtos)

Thank you for the feature request!
