### ISSUE TITLE
Abstract object types don't inlcude filterable relations

### ISSUE THREAD

**Issue by ikottman** [doug-martin/nestjs-query#399]
Filterable relations are lost when extending an abstract object type (added in https://github.com/doug-martin/nestjs-query/issues/82). 

Something similar to what was done for [FilterableFields](https://github.com/doug-martin/nestjs-query/commit/5151ceb08e05a435be4f367f6f6f03568bc72a27#diff-5045e0d24dc0ae16220a82ec079b41f0) needs to be done for [relations](https://github.com/doug-martin/nestjs-query/blob/bb72af000584256a734c88322b8396d0a70f2fdb/packages/query-graphql/src/metadata/metadata-storage.ts#L145)

**Comment by doug-martin** [comment]
@ikottman this has been fixed in `@nestjs-query/query-graphl@v0.17.6`

Thanks!
