### ISSUE TITLE
Support guards for read endpoint

### ISSUE THREAD

**Issue by izundo-viennv** [doug-martin/nestjs-query#40]
@doug-martin I read in docs about guards for read endpoint, but it'll be unreasonale if we can't support that, because if the user don't have permissions to query an endpoint, so how to do it, it seems that the library is just for public query

**Comment by doug-martin** [comment]
You can set guards on read endpoints just like the mutations.

```ts
@Resolver(() => ExampleDTO)
class Example extends CRUDResolver(ExampleDTO, {
  read: { guards: [AuthGuard] },
}) {
  constructor(readonly service: ExampleService) {
    super(service);
  }
}
```

 If you want them to apply to the entire resolver you can annotate your resolver

```ts
@UseGuards(AuthGuard)
@Resolver(() => ExampleDTO)
class Example extends CRUDResolver(ExampleDTO) {
  constructor(readonly service: ExampleService) {
    super(service);
  }
}
```

Hope this helps!

**Comment by izundo-viennv** [comment]
@doug-martin Can it support guards for relations?

**Comment by doug-martin** [comment]
Oh good point Ill update the docs to remove that warning. I tested locally and the read endpoints work find.

Ill need to test relations

**Comment by doug-martin** [comment]
Now that I have the e2e tests PR out, Ill add some tests around this and see if there is a fix, or if this is a limitation of nest with type-graphql.

**Comment by doug-martin** [comment]
For relations you will need to follow the same directions that are laid out here https://github.com/nestjs/graphql/issues/295#issuecomment-511191060

This is not a limitation of `nestjs-query` but https://github.com/nestjs/graphql. I will add something to the documentation to call this out to prevent confusion.

**Comment by doug-martin** [comment]
Reading the docs put out the section you called out was under the `Relations` docs which is correct. I updated them to call out they `guards`, `interceptors` and `filters` will not work for relations instead of the `read` endpoints.
