### ISSUE TITLE
Unable to inject service into custom CRUD resolver after updating to latest version of @nestjs-query/query-graphql.

### ISSUE THREAD

**Issue by mmChuckie** [doug-martin/nestjs-query#404]
First of all, thanks for providing this amazing package!

I have a custom UserResolver that injects a QueryService:
```
@Resolver(() => UserDTO)
export class UserResolver extends CRUDResolver(UserDTO) {
  constructor(
    @InjectQueryService(User)
    readonly service: QueryService<UserDTO>,
  ) {
    super(service);
  }
```
... which after updating to @nestjs-query/query-graphql@0.17.4 gives me this error:
`Class 'UserResolver' incorrectly extends base class 'CRUDResolver<UserDTO, DeepPartial<UserDTO>, DeepPartial<UserDTO>, ReadResolverOpts<UserDTO>>'.
  Types of property 'service' are incompatible.
    Type 'QueryService<UserDTO>' is missing the following properties from type 'QueryService<UserDTO>': aggregate, aggregateRelationsts(2415)`

I can provide more code if needed. Thanks!

**Comment by doug-martin** [comment]
What versions are you using for the other packages?

**Comment by mmChuckie** [comment]
Fixed after updating to latest version of core package. Thanks for the help.
