### ISSUE TITLE
Add ability to easily apply sorting

### ISSUE THREAD

**Issue by dylanstanfield** [doug-martin/nestjs-query#405]
Looking for something that works similarly to `applyFilter` for sorting.

**Comment by doug-martin** [comment]
@dylanstanfield I just published `v0.17.7` that includes an `applySort` method. As part of this release I also added `applyPaging` and `applyQuery`. I also added documentation around the utility methods you can check them out [here](https://doug-martin.github.io/nestjs-query/docs/utilities/query-helpers)

Thank you for submitting!
