### ISSUE TITLE
[Question] Get Underlying Entity Object

### ISSUE THREAD

**Issue by johannesschobel** [doug-martin/nestjs-query#41]
Dear @doug-martin ,

i recently had the problem, that i had to get the underlying `Entity` from the `Service` in order to call another service. For example, i have a the following situation:
```ts
export class UserService extends TypeOrmQueryService<UserObject, UserEntity> {...}
export class EvaluationService extends CoreService {...}
```

where the `UserService` is bootstrapped with your library, and the `EvaluationService` uses my own logic and provides other logic. Respective `EvaluationService` has a method which needs the `UserEntity`.

When i call the `this.userService.getById(id)` method, provided by the `UserService` class, however, i only get the `UserObject` and not the `UserEntity`. Note that the `Object` and `Entity` have different fields (i.e., the `Entity` has fields that are not present in the `Object`).

What is the *best / proper* way to get the underlying `Entity` from a `Service`?
Currently, I do it like this, however, i doubt that this is the best approach ;)

```ts
const user = await this.userService.getById(id);
const userEntity = this.userService
  .assemblerService
  .getAssembler(UserObject, UserEntity)
  .convertToEntity(user);
```

I know that the `UserService` also exposes the underlying `Repository` that is used for all operations. However, using the `plain repository` requires me to kind of re-write the queries :(

All the best and thanks a lot for your help!
Johannes

**Comment by izundo-viennv** [comment]
Hi @doug-martin 
If you want to get an entity instead of a dto, so you can implement code like this:

`user.service.ts` file:
```typescript
@QueryService(UserDTO)
export class UserService extends TypeOrmQueryService<UserDTO, User> {
  constructor(@InjectRepository(User) repo: Repository<User>) {
    super(repo);
  }
}
```

`user.resolver.ts` file:
```typescript
@Resolver(() => UserDTO)
export class UserResolver extends CRUDResolver(UserDTO) {
  constructor(readonly service: UserService) {
    super(service);
  }

  @Query(() => User)
  async findById(id: string): Promise<User> {
    return this.service.repo.findById(id);
  }
}
```

**Comment by doug-martin** [comment]
Hmm, I see your conundrum. When designing the services, I chose to expose the DTO since the entity/persistence layer is ultimately irrelevant to the CRUD piece of the framework. 

There currently isn't a much cleaner way to do this (Sorry about that) but Ill look into making the `AssemblerService` injectable by exposing a module.

**Comment by johannesschobel** [comment]
Dear @doug-martin ,

may i propose a suggestion?
I would like to see the `query-typeorm` and `query-graphql` package to **not** be linked together. Currently, the `typeorm` package kind of requires the `graphql` package, as the `QueryService` needs to be instantiated with the `DTOs` (`ObjectType`s). I know, that this is not a real dependency - however, it is a weak one (in my opinion).

I would like to have the `Service` layer return pure (!) `TypeORM Entities`, because there may be some kind of logic that requires the pure entities. Further, in my application scenario, i need to "duplicate" some of my endpoints to accept plain `http REST` calls. My own clients (i.e., mobile devices) are capable of working with the graphql API, however, there is a 3rd party customer also working with this API - and he is not able to make graphql calls - but only "pure" restful http calls. In this case, i would need to "rewrite" the service layer, because the current service layer returns objects and not entities. Finally, returning objects would hurt the "separation of duties" principle - as the service layer now has 2 different purposes: communicating with the database **and** converting from `Entity` to `Object`.

From my investigation, it looks like, that every method in the `Service` calls the `assembler.convertToX()` method. Wouldn't it be possible to:
1) make the `Assembler` an injectable `Service`
2) inject this `assemblerService` into the `Resolver`
3) call the `convertToX()` method yourself?

In this case, we may want to add "convenience" methods that convert a list of entities to a list of objects and so on..

In general, this would, of course, increase the "workload" a developer has to do when working with your library. However, i believe, that it will also enhance the maintainability of the developed applications. Separation of duty would be easier to handle, and so on. What do you think?

All the best,
Johannes

**Comment by doug-martin** [comment]
@johannesschobel this has been addressed in `v0.6.0` I created a [migration guide](https://doug-martin.github.io/nestjs-query/docs/migration-guides/v0.5.x-to-v0.6.x/) to explain some of the changes.

In short the TypeOrmQueryService changes were reverted the previous state, and a new `AssemblerQueryService` was introduced that will wrap another service to act as the translator. 

I also added a new decorator `InjectTypeOrmQueryService` so you dont have to define a `TypeOrmQueryService` unless you need to. 

```
import { AssemblerQueryService, QueryService } from '@nestjs-query/core';
import { InjectTypeOrmQueryService } from '@nestjs-query/query-typeorm';
import { TodoItemDTO } from './todo-item.dto';
import { TodoItemAssembler } from './todo-item.assembler';
import { TodoItemEntity } from './todo-item.entity';

@QueryService(TodoItemDTO)
export class TodoItemService extends AssemblerQueryService<TodoItemDTO, TodoItemEntity> {
  constructor(
    assembler: TodoItemAssembler,
    @InjectTypeOrmQueryService(TodoItemEntity) queryService: QueryService<TodoItemEntity>,
  ) {
    super(assembler, queryService);
  }
}
```

**Comment by johannesschobel** [comment]
Dear @doug-martin ,
damn, you're awesome! thanks for the migration guide. I am currently reading your description and will try to upgrade to the latest version. Looks kind of awesome ;) Let you know, how it went :laughing:

**Comment by johannesschobel** [comment]
Dear @doug-martin ,

ok, i just updated to the latest version, and it kind-of-works. However, i have a question - in order to better understand your approach:

Now (as of version `0.6.x`) it works like this:
1) i create a service that returns my entities from the database
2) i inject this service in my resolver
3) the plain service now returns `entities` instead of `objects`. These `entities` now needs to be converted to `objects` to be returned. But where?!

As stated in the docs and discussed in detail in this issue, the service should return `Entities` and not `ObjectTypes`. However, in the migration guide you state:
> In previous versions of nestjs-query the QueryService would automatically translate between your DTO and database type. This created a soft-dependency between the persistence service and the view layer. In v0.6.0 AssemblerQueryService was introduced to handle translating between your DTO and persistence type.

So the translating stuff is - kind of - **still** happening in a service, right?
I thought the `mapping` between `Entity` and `Dto` would be handled in the `Resolver`?

So what would be the "workflow" for my initially described use-case?
Should i create a plain service that offers my custom database-query logic and business logic. This service is then wrapped in an additional `AssemblerService`. And this `AssemblerService` is injected in the `Resolver`?

I hope you know, what i mean!?
All the best,
Johannes
