### ISSUE TITLE
[Question] Relations with ReadResolver can't query relations

### ISSUE THREAD

**Issue by izundo-viennv** [doug-martin/nestjs-query#42]
@doug-martin I created a resolver extends from `ReadResolver` but it doesn't doesn't generate schema for query relations

**Comment by doug-martin** [comment]
I went back and forth on whether or not the read resolver should automatically add relations. When using the read resolver by itself its picking a la carte functionality. 

Looking at the source I see that I dont expose the Relateable mixin....Ill look into either exposing that or automatically adding the read relations.

The reason I wavered, was that It was unclear where the add/remove relations belonged, and I felt it kinda broke the single responsibility of the Read Resolver.
