### ISSUE TITLE
Update to a relation, does not update the relation

### ISSUE THREAD

**Issue by renehauck** [doug-martin/nestjs-query#420]
Hi,

I just saw that an update to a relation does not traditionally update the relation, but simply adds another entry.

For example:

I copied the example "basic" from you, but extended "todo-item-update.dto.ts" and "todo-item-input.dto.ts" with the field "tags". Furthermore, I have added the option "cascade" to "todo-item.entity.ts" at tags.

`todo-item-input.dto.ts`
```typescript
import { Field, InputType } from '@nestjs/graphql';
import { TagInputDTO } from '../../tag/dto/tag-input.dto';

@InputType('TodoItemInput')
export class TodoItemInputDTO {
  @Field()
  title!: string;

  @Field()
  completed!: boolean;

  // new
  @Field(type => [TagInputDTO])
  tags: TagInputDTO[];
}
```
`todo-item-update.dto.ts`
```typescript
import { Field, InputType } from '@nestjs/graphql';
import { TagInputDTO } from '../../tag/dto/tag-input.dto';

@InputType('TodoItemUpdate')
export class TodoItemUpdateDTO {
  @Field({ nullable: true })
  title?: string;

  @Field({ nullable: true })
  completed?: boolean;

  // new 
  @Field(type=>[ TagInputDTO])
  tags:TagInputDTO[]
}
```
`todo-item.entity.ts`
```typescript
import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
  OneToMany,
  ManyToMany,
  JoinTable,
} from 'typeorm';
import { SubTaskEntity } from '../sub-task/sub-task.entity';
import { TagEntity } from '../tag/tag.entity';

@Entity({ name: 'todo_item' })
export class TodoItemEntity {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column()
  title!: string;

  @Column({ nullable: true })
  description?: string;

  @Column()
  completed!: boolean;

  @OneToMany(() => SubTaskEntity, (subTask) => subTask.todoItem)
  subTasks!: SubTaskEntity[];

  @CreateDateColumn()
  created!: Date;

  @UpdateDateColumn()
  updated!: Date;

  // cascade is new
  @ManyToMany(() => TagEntity, (tag) => tag.todoItems,{cascade:true})
  @JoinTable()
  tags!: TagEntity[];
}

```
Now I execute a create mutation and automatically create a tag "Test".
![image](https://user-images.githubusercontent.com/3898144/88789600-3b194480-d197-11ea-9faa-eb7ba475b436.png)

After that I want to replace the tag array with "Dog" based on the id via the mutation "updateOneTodoItem". 
![image](https://user-images.githubusercontent.com/3898144/88789973-b844b980-d197-11ea-883e-a5e8794e0f6a.png)

This works fine, but when I look into the database now, I suddenly have 2 entries.
![image](https://user-images.githubusercontent.com/3898144/88790086-e629fe00-d197-11ea-92ed-b190dc0696f2.png)

Something like that could quickly fill the database :confused: 

Thanks for your work!

**Comment by doug-martin** [comment]
@renehauck it looks like your examples are bypassing nestjs-query to add relations, instead relying on typeorm. I could be wrong but I suspect if you included an `id` on the relation typeorm would try to find an existing record but I could be wrong. 

Because of this and cascade can lead to oddities like this nestjs-query exposes two endpoints to mutate relations. This example is a many to many so you could use the `addTagsToTodoItem` and removeTagsFromTodoItem` both methods expect an id and relationIds you can read more about the exposed mutations [here](https://doug-martin.github.io/nestjs-query/docs/graphql/relations#resolver-2)

Typeorm also includes a warning about [cascades](https://typeorm.io/#/relations/cascades) this which also lead me create the additional endpoints. 

```
Keep in mind - great power comes with great responsibility. Cascades may seem like a good and easy way to work with relations, but they may also bring bugs and security issues when some undesired object is being saved into the database. Also, they provide a less explicit way of saving new objects into the database.
```

Hope this helps!

**Comment by renehauck** [comment]
@doug-martin  You were absolutely right, if I give an Id for each element, the update works fine. I think you can see that I come from the NoSQL corner. :smile: 
It is also logical that the id must be included.

Thanks for the help!

**Comment by wowczarczyk** [comment]
@doug-martin  Are there any plans to support nested objects in mutations in `nestjs-query`? So I could add a TodoItem together with an array of SubTasks in one go (mutation)?

**Comment by renehauck** [comment]
It may even be possible to set flags to relations that set an update/delete/create connection.
For example a "delete" will automatically delete all relations of the deleted entry. An "update" takes the whole update object into account and updates the connected relations. 
I think the "create obj" is already fully considered, right?
What do you guys think?

Thanks for the work!
