### ISSUE TITLE
[Question]About Authorization

### ISSUE THREAD

**Issue by boxcc** [doug-martin/nestjs-query#445]
How to deal with authorization issues in nestjs-query?

E.g:  [https://graphql.org/learn/authorization/](https://graphql.org/learn/authorization/)

I have completed the jwt verification, but I don’t know how to find personal data in ReadOne or ReadMany. I hope to give me some pointers. Thank you very much.

I think we can use [hooks](https://doug-martin.github.io/nestjs-query/docs/graphql/hooks) to handle create/update/detele.

**Comment by doug-martin** [comment]
@boxcc you can use [guards](https://docs.nestjs.com/guards) to secure your endpoints. Take a look at https://doug-martin.github.io/nestjs-query/docs/graphql/resolvers#guards-pipes-filters-and-interceptors for a quick example.

**Comment by boxcc** [comment]
@doug-martin yes, I have completed the setting of guards, but I don't know how to filter out the data owned by users

**Comment by doug-martin** [comment]
@boxcc if you could provide a more complete example/description I may be able to point you in the right direction. 

Are you trying to set authorization on fields or entire objects? 
Can you alter the query to only return the information relevant to the consumer?
Can you use [extensions](https://docs.nestjs.com/graphql/extensions) to solve this?

Your question may be better suited for the [`@nestjs/graphql`](https://github.com/nestjs/graphql) but given the information I'm unsure.

**Comment by jlarmstrongiv** [comment]
@doug-martin Funny enough, I wrote a draft of a similar question but never posted it.  

I’m a bit confused figuring out how to use authentication and authorization with nestjs-query.  

I’m piecing together relevant pieces of the current documentation, but I’m not sure what the recommended way to achieve my goals.  Am I missing anything?

## Current documentation

- **[DTO filter](https://doug-martin.github.io/nestjs-query/docs/graphql/dtos#example---filterrequired)**
  - Make filterable fields required `@FilterableField({ filterRequired: true })`
- [**Resolver options**](https://doug-martin.github.io/nestjs-query/docs/graphql/resolvers#resolveroptions)
  - disabled=false - Set to true to disable all endpoints.
  - guards=[] - An array of guards to add to all endpoints.
  - one, many - Both the one and many accept the following options:
    - disabled=false - Set to true to disable the endpoint.
    - guards=[] - An array of guards to add to the endpoint.
  - Use the code toggle to see the difference in the NestjsQueryGraphQLModule vs CRUDResolver.  
- **[Resolver custom methods](https://doug-martin.github.io/nestjs-query/docs/graphql/resolvers#custom-methods)**
  - Custom methods to create queries, like `completedTodoItems`. 
- [**Resolver guards**](https://doug-martin.github.io/nestjs-query/docs/graphql/resolvers/#guards-pipes-filters-and-interceptors)
  - Apply guards to resolvers, like `create: { guards },`.  However, it’s missing documentation for read, which seems to be [supported](https://github.com/doug-martin/nestjs-query/issues/40).
- [**Aggregations**](https://doug-martin.github.io/nestjs-query/docs/graphql/aggregations)
  - Add filters to aggregations, for both ObjectTypes and Relations, like `filter: { completed: { is: false } }`
- **[Hooks](https://doug-martin.github.io/nestjs-query/docs/graphql/hooks)** 
  - Hooks to add the user in create, update, and delete for one and many.  However, it’s missing examples for @BeforeDeleteOne and @BeforeDeleteMany.  In addition, there don’t seem to be hooks for queries (get one, get many), which would be very useful.
- **[Relation disable operations](https://doug-martin.github.io/nestjs-query/docs/graphql/relations/#disable-reads)**
  - Disable operations, like remove `@Relation('todoItem', () => TodoItemDTO, { disableRemove: true })` 
- **[Relation guards](https://doug-martin.github.io/nestjs-query/docs/graphql/relations/#guards-pipes-and-filters)**
  - Set guards on relations, like `@Relation('todoItem', () => TodoItemDTO, { guards: [AuthGuard] })`

## Examples
It would be nice to setup an example with authentication and authorization with passport, bcrypt, signup, login, guards, and a me/user query.  I feel like a generic example like this should cover a lot of use cases:

- Authentication:  Usernames are public, but user emails are private.
- Authentication:  Create a post or create a comment.
- Authentication:  Posts should be able to be either public or private.  A user can query their own private posts.  
- Authentication:  Authors should be able to delete comments, but commenters should not be able to delete posts.  
- Authentication:  Users should be able to perform private crud operations on their own comments.  
- Authentication:  Users should be able to see their personal total post and comment count.
- Authorization:  Admins should be able to see all users and assign roles.
- Authorization:  Editors should be able to edit any post and comment.
- Authorization:  Editors should be able to see the total number of posts and comments.

**Comment by boxcc** [comment]
> @boxcc if you could provide a more complete example/description I may be able to point you in the right direction.
> 
> Are you trying to set authorization on fields or entire objects?
> Can you alter the query to only return the information relevant to the consumer?
> Can you use [extensions](https://docs.nestjs.com/graphql/extensions) to solve this?
> 
> Your question may be better suited for the [`@nestjs/graphql`](https://github.com/nestjs/graphql) but given the information I'm unsure.

@doug-martin If I use nestjs/graphql, I will write code in this way:

roles.guard
```
import { ExecutionContext, Injectable, CanActivate } from '@nestjs/common';
import { AuthGuard } from '@nestjs/passport';
import { GqlExecutionContext } from '@nestjs/graphql';
// import { AuthenticationError } from 'apollo-server-core';
import { Reflector } from '@nestjs/core';
import { ExecutionContextHost } from '@nestjs/core/helpers/execution-context-host';

@Injectable()
export class RolesGuard extends AuthGuard('jwt') {
  constructor(private readonly reflector: Reflector) {
    super();
  }

  async canActivate(context: ExecutionContext) {
    const roles = this.reflector.get<string[]>('roles', context.getHandler());
    if (!roles) {
      return true;
    }

    const ctx = GqlExecutionContext.create(context);
    const { req } = ctx.getContext();

    const result = await super.canActivate(new ExecutionContextHost([req]));
    if (!result || !req.user) {
      return false;
    }

    return this.matchRoles(roles, req.user.role);
  }

  matchRoles(roles: string[], userRoles: string) {
    return roles.includes(userRoles);
  }
}
```

user.decorator
```
import { createParamDecorator, ExecutionContext } from '@nestjs/common';
import { GqlExecutionContext } from '@nestjs/graphql';

export const CurrentUser = createParamDecorator(
  (data, context: ExecutionContext) => {
    const ctx = GqlExecutionContext.create(context);
    return ctx.getContext().req.user;
  },
);
```

resolver
```
  @Roles('Member')
  @Query(() => Articles)
  async user(@CurrentUser() user: Users) {
    return this.articleService.findMemberArticleByUserId(user.id);
  }
```

service
```
async findMemberArticleByUserId(userId: string) {
    return this.articleRepository.find({ userId });
}
```

The problem I encountered with nest-query is that I don’t know how to filter out the member articles in the example.

**Comment by doug-martin** [comment]
Hi All,

Quick update, now that I have had the time to dive into this problem, I'm working on some changes to make this easier. It will require some passive changes to the query-service to allow setting of filters based on authorization.

I'm playing with a couple of options to allow for this and I'm not sure which way will provide the cleanest API, but I think I'll add either an `@Auth` decorator that you can decorate the DTO with so you can use the context to create a filter that should be applied when doing queries or mutations to ensure that the user has the ability to read or mutate the data. Or allow you to set the auth on the resolver options, I'm leaning towards the former to keep the API consistent. 

This change will also include before hooks for the query methods for anything additional that may not fall in the realm of Auth. 

I'll also include a fully functioning auth example that will use passport JWT. 

I hope to have something out over the next week or so.

**Comment by jlarmstrongiv** [comment]
@doug-martin Wow, glad to hear the update 🎉 thanks for being awesome, can’t wait to give it a try

**Comment by boxcc** [comment]
I am trying to use  [directives ](https://docs.nestjs.com/graphql/directives) to solve

### Code:
auth.directive.ts
```
import { SchemaDirectiveVisitor } from 'apollo-server';
import { defaultFieldResolver, GraphQLField } from 'graphql';
import * as jwtdecode from 'jwt-decode';
import { Payload } from '@/types';

export class AuthDirective extends SchemaDirectiveVisitor {
  visitFieldDefinition(field: GraphQLField<any, any>) {
    const { resolve = defaultFieldResolver } = field;
    field.resolve = async function(...args) {
      const user = jwtdecode<Payload>(args[2].req.headers.authorization);
      if (!user || !user.id) {
        return [];
      }

      args[1].filter = { userId: { eq: user.id } };
      const result = await resolve.apply(this, args);
      return result;
    };
  }
}
```

module
```
...
...

@Module({
  imports: [
    NestjsQueryGraphQLModule.forFeature({
      imports: [NestjsQueryTypeOrmModule.forFeature([MemberArticles])],
      resolvers: [
        {
          DTOClass: MemberArticles,
          EntityClass: MemberArticles,
          pagingStrategy: PagingStrategies.OFFSET,
          read: { decorators: [Directive('@auth'), Roles('Member')] },
          enableAggregate: false,
        },
      ],
    }),
  ],
})
export class MemberArticleModule {}

```

This method can achieve filtering membership data, but I found a problem Directive runs before the role.guard code

**Comment by doug-martin** [comment]
@boxcc that will work for some cases, but when finding by id, updating by id, or deleing by id. Any user could fetch the info. My changes will address that.

**Comment by wowczarczyk** [comment]
Are you planning to implement field level authorization as well?

**Comment by doug-martin** [comment]
@wowczarczyk not as part of the changes I'm currently making. The changes I'm making currently are already pretty invasive, and I dont want to expand the scope of the current feature beyond authorization for dtos and relations.

**Comment by doug-martin** [comment]
Hi All,

I just issues the PR to add authorization for queries and mutations. You can read the unpublished docs [here](https://github.com/doug-martin/nestjs-query/blob/auth/documentation/docs/graphql/authorization.mdx)

Its a pretty big change because I had to change the query service to allow additional filtering for certain methods. I'll update once I publish!

**Comment by jlarmstrongiv** [comment]
Went to check out the changes and spin up a project today, here’s the [updated link](https://github.com/doug-martin/nestjs-query/blob/master/documentation/docs/graphql/authorization.mdx) 😄

**Comment by doug-martin** [comment]
I just published the latest version `v0.19.0`! 

You can check out the published docs [here](https://doug-martin.github.io/nestjs-query/docs/graphql/authorization)

**Comment by jlarmstrongiv** [comment]
@doug-martin the docs and example are quite helpful!  Especially the custom queries like `completedTodoItems`.  It would be nice to add a signup mutation and bcrypt to the example, as these are common anytime someone implements authentication.  Personally, I’m experimenting with authorizers that use roles too.  Very cool so far.

**Comment by doug-martin** [comment]
@jlarmstrongiv I'm glad to hear you're finding them useful! Feel free to issue a PR to update/clarify any thing you found confusing or could use more explaination.

I tried to keep the authentication piece as generic as possible as that is separate from the Authorization piece. Plus there are so many ways to go about authorization I didnt want to push anyone down an certain path. The important piece is that you need information in the context.
