### ISSUE TITLE
[Discussion] Architecture design for service classes

### ISSUE THREAD

**Issue by izundo-viennv** [doug-martin/nestjs-query#45]
@doug-martin @johannesschobel  I'm thinking about you should come with another solution for service classes. Service classes are now depending on DTOs, so it's hard to custom if you have multiple dtos for one entity and you must have multiple services relatively. For example if I have UserDto1 with `firstName`, `lastName` used by web app and UserDto2 with `firstName`, `lastName`, `isDeleted`, `roles`, `permissions` used by admin app, so I have to create 2 two services for that.

My idea: Service should only return entities, it shoudn't depend on dtos and we will have a mechanism to mapping to any dto we want to return from resolvers. I know that is a big change, but we will address a lots of problems (**Get Underlying Entity Object**, **Restricting fields returned and fields can be filtered if the user doesn't have permissions**, ...). How do you think?

**Comment by johannesschobel** [comment]
can we close this issue in favour of the original one in #41 ? otherwise we have discussion in multiple  places :)

**Comment by doug-martin** [comment]
@johannesschobel I agree moving to #41.
