### ISSUE TITLE
Error when putting Field decorator on object

### ISSUE THREAD

**Issue by yacovg** [doug-martin/nestjs-query#485]
I'm getting error when using @Field() decorator with other entities.
It's working fine with plain graphql (not using this library)

@ObjectType()
@Entity()
export class CustomerModel {
  @Field()
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @FilterableField()
  @Column({ length: 500, nullable: false })
  name: string;

  @Field()
  @Column('text', { nullable: false })
  email: string;

  @Field()
  @Column('varchar', { length: 15 })
  phone: string;

  @Field()
  @Column('text')
  address: string;

  @Field(type => [InvoiceModel], { nullable: true })
  @OneToMany(
    type => InvoiceModel,
    invoice => invoice.customer,
  )
  invoices: InvoiceModel[];
}

@ObjectType()
@Entity()
export class InvoiceModel {
  @Field()
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Field()
  @Column({ length: 500, nullable: false })
  invoiceNo: string;

  @Field()
  @Column('text')
  description: string;

  @Field(type => CustomerModel)
  @ManyToOne(
    type => CustomerModel,
    customer => customer.invoices,
  )
  customer: CustomerModel;
}

(node:6121) UnhandledPromiseRejectionWarning: Error: Cannot determine a GraphQL input type for the "invoices". Make sure your class is decorated with an appropriate decorator.
    at InputTypeFactory.create (/tmp/invoice-app/node_modules/@nestjs/graphql/dist/schema-builder/factories/input-type.factory.js:19:23)
    at /tmp/invoice-app/node_modules/@nestjs/graphql/dist/schema-builder/factories/input-type-definition.factory.js:44:52
    at Array.forEach (<anonymous>)
    at /tmp/invoice-app/node_modules/@nestjs/graphql/dist/schema-builder/factories/input-type-definition.factory.js:42:33
    at resolveThunk (/tmp/invoice-app/node_modules/graphql/type/definition.js:478:40)
    at defineInputFieldMap (/tmp/invoice-app/node_modules/graphql/type/definition.js:1203:18)
    at GraphQLInputObjectType.getFields (/tmp/invoice-app/node_modules/graphql/type/definition.js:1151:27)
    at TypeFieldsAccessor.extractFromInputType (/tmp/invoice-app/node_modules/@nestjs/graphql/dist/schema-builder/services/type-fields.accessor.js:9:35)
    at /tmp/invoice-app/node_modules/@nestjs/graphql/dist/schema-builder/factories/input-type-definition.factory.js:56:66
    at resolveThunk (/tmp/invoice-app/node_modules/graphql/type/definition.js:478:40)

**Comment by sebargarcia** [comment]
the decorator is **@Filed** with an F uppercase

**Comment by doug-martin** [comment]
@yacovg take a look at https://doug-martin.github.io/nestjs-query/docs/persistence/services#relations you should remove the `@Field` decorator on the `invoices` field and add a the `Connection` decorator. You can read more about relations in `nestjs-query` [here](https://doug-martin.github.io/nestjs-query/docs/graphql/relations)
