### ISSUE TITLE
Export GraphQL SDL without running the entire application

### ISSUE THREAD

**Issue by KoenLav** [doug-martin/nestjs-query#489]
We would like to export the GraphQL SDL to a file using a command. Currently we run the application and use setTimeout to kill it after x seconds (to allow the application to startup and export the schema), but this is not ideal.

We've already taken a look at: https://docs.nestjs.com/graphql/generating-sdl#generating-sdl

Could someone give us some pointers as to whether and how we could get the Resolvers as generated by Nestjs-Query without running the entire application?

Any help would be appreciated, but I can also imagine this could be a feature (CLI command).

**Comment by marian2js** [comment]
I guess you are generating your schema with the autoSchemaFile option. If so, you can solve this with a new [standalone application](https://docs.nestjs.com/standalone-applications).

The new standalone app would only need a main file which should look like this:

```ts
async function bootstrap () {
 const app = await NestFactory.create(AppModule) // AppModule should be the module that is exporting the schema
 await app.init()
 await app.close()
}

bootstrap()
```

**Comment by KoenLav** [comment]
That worked, thanks!

Changed our project structure to monorepo, added a standalone app and simply imported the AppModule and it worked :)
