### ISSUE TITLE
Extending an abstract class with hooks

### ISSUE THREAD

**Issue by priya1712d** [doug-martin/nestjs-query#524]
I am trying to run base class hooks, every time the child class is resolved.

**Base class**
```
@BeforeCreateOne((input: CreateOneInputType<any>, context: GqlExecutionContext) => {
  input.input.modifiedBy = "some code";
  return input;
})
@InputType({isAbstract: true})
export abstract class Base {}

```

**Child class**
```
@InputType()
export class Child1 {
@Field(Returns(String), { defaultValue: '' })
modifiedBy?: string;
}
```

But hook seems not to be working anymore. I am pretty sure I was able to run this few days back.
My motivation is to add hooks at one place for a column eg modified_by and then use it in multiple children classes.

**Comment by doug-martin** [comment]
@priya1712d fix has been published under `v0.19.3`

**Comment by doug-martin** [comment]
Thank you for filing a bug report!

**Comment by priya1712d** [comment]
@doug-martin Thank you so much for such quick response.
