### ISSUE TITLE
I can't find a way to convert a typeorm query result into a cursor-based response

### ISSUE THREAD

**Issue by hugohernani** [doug-martin/nestjs-query#537]
First of all, thanks for the incredible framework!

## Is there any helper method that transform a typeorm query result into a cursor-based response?

I've being try to add a custom method into a custom resolver (using CRUDResolver) but I can't figure it out how to transform a collection of entities into a cursor-based response.

**Comment by doug-martin** [comment]
@hugohernani thank you!

Yep, you can do this in a custom resolver, check out
* https://github.com/doug-martin/nestjs-query/blob/master/examples/typeorm/src/todo-item/todo-item.resolver.ts#L13-L22
* https://github.com/doug-martin/nestjs-query/blob/master/examples/typeorm/src/todo-item/types.ts

I hope this helps!

**Comment by hugohernani** [comment]
awesome!

Thank you, @doug-martin!
