### ISSUE TITLE
How to get custom typeorm service to be accesible within custom resolver?

### ISSUE THREAD

**Issue by hugohernani** [doug-martin/nestjs-query#538]
Looking into doc I realized the framework allows a service to be customized: https://doug-martin.github.io/nestjs-query/docs/persistence/typeorm/custom-service

The docs seems to show that once the custom **TodoItemService** is injected into autogenerated resolvers, their included method (`markAllAsCompleted`) will be available somewhere (??). I can't figure this out.

But my case goes somehow further.
I've defined a custom service:

```node
@QueryService(PostDTO)
export class PostService extends TypeOrmQueryService<PostEntity> {
  constructor(@InjectRepository(PostEntity) repo: Repository<PostEntity>) {
    super(repo)
  }

  async getTruncatedPosts(
    incomingQuery: Query<PostDTO>,
    attr: string,
    size: number = 200
  ): Promise<PostDTO[]> {
    const entities = await this.query(incomingQuery)

    console.log(entities);

    return entities.map((entity) => {
      const postDTO = new PostDTO();
      // it would also be good to call a helper or an assembler to do the entity/dto converstion as well
      postDTO[attr] = _.truncate(entity[attr], {
        length: 200,
        separator: /,? +/,
      })
      return postDTO;
    })
  }
}

```

then I created a resolver with **PostConnection** and **PostQuery** set as [documentation](https://doug-martin.github.io/nestjs-query/docs/graphql/resolvers#custom-methods) describes:
```node
@Resolver(() => PostDTO)
export class PostResolver extends CRUDResolver(PostDTO) {
  constructor(
    @Inject(PostService) // InjectAssemblerQueryService does not recognize my service
    readonly service: PostService
  ) {
    super(service)
  }

  // Set the return type to the TodoItemConnection
  @Query(() => PostConnection)
  truncatedPosts(@Args() query: PostQuery): Promise<ConnectionType<PostDTO>> {
    const result = this.service.getTruncatedPosts(query, 'content');
    // console.log(result) // if I console out this I can see that I am fetching the result I want to
    return PostConnection.createFromPromise((q) => this.service.getTruncatedPosts(q, 'content'), query);
  }
```

The issue is that truncatedPosts does not return result. It returns empty. How can I connect a custom service into a custom resolver and also using an assembler on them?

**Comment by hugohernani** [comment]
This is my module setup:

```node
@Module({
  imports: [
    TypeOrmModule.forFeature([AuthorEntity, PostEntity, CommentEntity]),
    NestjsQueryGraphQLModule.forFeature({
      imports: [
        NestjsQueryTypeOrmModule.forFeature([
          AuthorEntity,
          PostEntity,
          CommentEntity,
        ]),
      ],
      assemblers: [PostAssembler],
      resolvers: [
        {
          DTOClass: AuthorDTO,
          EntityClass: AuthorEntity,
        },
        {
          DTOClass: CommentDTO,
          EntityClass: CommentEntity,
        },
      ],
    }),
  ],
  providers: [PostService, PostResolver],
})
export class ArticlesManagementModule {}

```

**Comment by doug-martin** [comment]
@hugohernani because your using a custom service it will not automatically inject the assembler for you should instead extend the `AssemblerQueryService`

```ts
@QueryService(PostDTO)
export class PostService extends AssemblerQueryService<PostDTO> {
  constructor(
    readonly assembler: PostAssembler, 
    @InjectQueryService(PostEntity) readonly service: QueryService<PostEntity>
  ) {
    super(assembler, service)
  }

  async getTruncatedPosts(
    incomingQuery: Query<PostDTO>,
    attr: string,
    size: number = 200
  ): Promise<PostDTO[]> {
      // using the query method will ensure you get PostDTOs back.
    const postDTOs = await this.query(incomingQuery)
    console.log(postDTOs);
    return postDTOs.map((postDTO) => {
      postDTO[attr] = _.truncate(postDTO[attr], {
        length: 200,
        separator: /,? +/,
      })
      return postDTO;
    })
  }
}
```

As for why your not getting back results, I'm not entirely sure. Are you just getting an empty connection back? Does the console.log log out DTOs? You may try the new service and let me know if you still have issues.

**Comment by hugohernani** [comment]
Thanks, @doug-martin !

yes. The console out, called on PostsResolver -> truncatedPosts, gives me the result.
The issue is the the query function inside createFromPromise does not seem to be called and I do not know the reason.
`return PostConnection.createFromPromise((q) => this.service.getTruncatedPosts(q, 'content'), query);`

I liked what you did by extending AssemblerQueryService<PostDTO>. I'll give this a try. Thanks!

**Comment by doug-martin** [comment]
@hugohernani do you have the validation pipe enabled? Similar to https://github.com/doug-martin/nestjs-query/blob/master/examples/basic/src/main.ts#L8 (in particular the `transform`) `nestjs-query` will always enforce the transformation for its own methods, but I'm curious if you are not getting an instance of PostQuery but instead the raw payload without any paging defaults.

**Comment by hugohernani** [comment]
awesome, @doug-martin !

That was exactly the issue. I didn't enable validation/transform before.
I was considering that PostConnection.createFromPromise was not returning anything due to service result not giving the expected result... When you mentioned validation/transform I tested and it worked. Thanks!
