### ISSUE TITLE
[Bug] Partial update fails with UpdateDTO

### ISSUE THREAD

**Issue by archer747** [doug-martin/nestjs-query#547]
Hi,

I noticed that partial update mutations fail when Update DTO is specified.

To reproduce using the sample [To do app](https://doug-martin.github.io/nestjs-query/docs/introduction/example#update-a-todoitem):

Add todo-item.update.dto.ts:

```
import { Int, GraphQLISODateTime, Field, InputType } from '@nestjs/graphql';
import { FilterableField } from '@nestjs-query/query-graphql';


@InputType('TodoItemUpdate')
export class TodoItemUpdateDTO {
  @FilterableField(() => Int)
  id!: number;

  @FilterableField()
  title!: string;

  @FilterableField()
  completed!: boolean;

  @Field(() => GraphQLISODateTime)
  created!: Date;

  @Field(() => GraphQLISODateTime)
  updated!: Date;
}

```

Add this to the resolvers in todo-item.module.ts:
`resolvers: [{ DTOClass: TodoItemDTO, EntityClass: TodoItemEntity, UpdateDTOClass: TodoItemUpdateDTO, }],`

Try the Update a TodoItem mutation:
```
mutation {
  updateOneTodoItem(input: { id: 3, update: { completed: false } }) {
    id
    title
    completed
    created
    updated
  }
}
```

**Comment by doug-martin** [comment]
@archer747 I'm assuming its because you are making all fields required, and are only passing in completed.

What about the following (adapted from https://github.com/doug-martin/nestjs-query/blob/master/examples/basic/src/todo-item/dto/todo-item-update.dto.ts)

```ts
import { IsString, MaxLength, IsBoolean, IsOptional } from 'class-validator';
import { Field, InputType } from '@nestjs/graphql';

@InputType('TodoItemUpdate')
export class TodoItemUpdateDTO {
  @Field({ nullable: true })
  title?: string;

  @Field({ nullable: true })
  completed?: boolean;
}
```

Hope this helps.

**Comment by archer747** [comment]
It worked. I did not realize that there is a requirement to make the fields nullable in the Update DTO as this was not required when Input/Update DTOs were not specified.

Thanks @doug-martin !

**Comment by doug-martin** [comment]
@archer747 `nestjs-query` does not require the fields to be `nullable`, by providing the custom update DTO and not setting the fields to nullable `@nestjs/graphql` made them were required. If for example you had a field that you required on every update, you should not make that nullable as you want to ensure the client provides a value. Similar to the create DTO you may have some fields that are required to create a new record while others are optional. 

The update DTO that nestjs-query creates for you when you don't provide a custom one is a partial when every field has `nullable` set to true. 

I hope that helps clarify! 
Have a great rest of your weekend!
