### ISSUE TITLE
NestJs 7,0 BREAKING CHANGES

### ISSUE THREAD

**Issue by johannesschobel** [doug-martin/nestjs-query#56]
Dear @doug-martin ,

i hope you are well?!
I just found out, that `nestjs v7.0` was released during the weekend. There are some really hard breaking changes, especially in the context of `GraphQL`. I am not sure if you already found the release notes:
https://trilon.io/blog/announcing-nestjs-7-whats-new#GraphQL-TypeScript

The most crucial change is, that the "code-first" approach with `type-graphql` was dropped. In this context, the `nestjs core team` created a similar package with a mostly identical external API. Basically, one need to change the imports from `type-graphql` to `@nestjs/graphql` - that should do the trick, that's what they write in their migration notes :laughing: 

do you have some more information?
stay well and keep up your great work,
Johannes

**Comment by doug-martin** [comment]
Hi @johannesschobel, yeah I saw this saturday!

I've alomost got it working, I have had to change some of the internals since its not as simple as their migration notes would lead you to believe. I hope to have a pr out today or tomorrow.

**Comment by johannesschobel** [comment]
damn, you're fast!

from the "developer using your library"-point-of-view: How much effort is it to switch from 6.x to 7.0? Is it only changing the imports and you're good to go?

All the best and stay safe

**Comment by doug-martin** [comment]
For the most part it will be changing from `type-graphql` to `@nestjs/graphql` and you will now need to register a module `NestjsQueryGraphqlModule` that will wire up the resolvers.

@nestjs/graphql changed how the decorators work entirely and resolver inheritance no longer works, so I'm having to change how the decorators work. 

Im still working on getting all the tests to pass so it may change more, but I'll post updates to this issue.

**Comment by doug-martin** [comment]
Well I hit a roadblock. Hopefully https://github.com/nestjs/graphql/issues/659 can be fixed soon.

**Comment by doug-martin** [comment]
Support for nest 7 is in `v0.7.0`

**Comment by johannesschobel** [comment]
you are awesome! thanks a lot for your work! :+1: i will try to upgrade to nest 7 next week and then upgrade to 0.7.x as well!

**Comment by johannesschobel** [comment]
worked like a charm - thanks a lot
