### ISSUE TITLE
Manually defined CRUDResolver type issue

### ISSUE THREAD

**Issue by reecemcd** [doug-martin/nestjs-query#561]
Version used (for all three @nestjs-query packages): `0.20.0`

We're testing out some capabilities of your awesome library. A big one for us is to have the ability to manually define our own resolver that we can use to extend functionality easily should edge cases arise. I'm really excited to see this is supported via the CRUDResolver, but seem to be having a typing issue when following along with the docs.

All I've done so far is follow the intro tutorial and then try to add a custom resolver. I've got:

The TodoDTO:
```typescript
import { FilterableField } from '@nestjs-query/query-graphql';
import { ObjectType, GraphQLISODateTime, Field, Int } from '@nestjs/graphql';

@ObjectType('TodoItem')
export class TodoItemDTO {
  @FilterableField(() => Int)
  id!: number;

  @FilterableField()
  title!: string;

  @FilterableField()
  completed!: boolean;

  @Field(() => GraphQLISODateTime)
  created!: Date;

  @Field(() => GraphQLISODateTime)
  updated!: Date;
}
```

The TypeORM entity:
```typescript
import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

@Entity()
export class TodoItemEntity {
  @PrimaryGeneratedColumn()
  id!: string;

  @Column()
  title!: string;

  @Column()
  completed!: boolean;

  @CreateDateColumn()
  created!: Date;

  @UpdateDateColumn()
  updated!: Date;
}
```

And finally the resolver:
```typescript
import { InjectQueryService, QueryService } from "@nestjs-query/core";
import { CRUDResolver } from "@nestjs-query/query-graphql";
import { Resolver } from "@nestjs/graphql";
import { TodoItemDTO } from "./todo-item.dto";
import { TodoItemEntity } from "./todo-item.entity";


@Resolver(() => TodoItemDTO)
export class TodoItemResolver extends CRUDResolver(TodoItemDTO) {
  constructor(
    @InjectQueryService(TodoItemEntity) readonly service: QueryService<TodoItemEntity>
  ) {
    super(service); // <-- Type Error Here
  }
}
```

The problem is, when passing the injected service to the parent constructor I get this type error:
```
Argument of type 'QueryService<TodoItemEntity, DeepPartial<TodoItemEntity>, DeepPartial<TodoItemEntity>>' is not assignable to parameter of type 'QueryService<TodoItemDTO, DeepPartial<TodoItemDTO>, DeepPartial<TodoItemDTO>>'
```

Is there some setup I'm missing here? The DTO and Entity appear to be the same shape. Help would be appreciated!

**Comment by doug-martin** [comment]
Hi @reecemcd!

I'm guessing this is a problem because the id's are two different types, could you try switching to a common types?

**Comment by reecemcd** [comment]
Ah that makes perfect sense. Can't believe I missed that. Thanks so much for the quick response!
