### ISSUE TITLE
[Question / Request]: Expose Repository in AssemblerService

### ISSUE THREAD

**Issue by johannesschobel** [doug-martin/nestjs-query#57]
Dear @doug-martin ,

and again - it's me, haha :laughing: ,
do you think, it would be possible to expose the `repo` of the `queryService` of the `assemblerService`?

Currently, i would need to inject both, the `DatabaseService` and the `AssemblerService` in the `Resolver`, if i want to access the low-level repository functions. I think, it would be better to just use
```ts
this.assemblerService.queryService.repo.xyz();
```

what do you think? Only downside I see, would be, that it couples the implementation to a specific ORM framework (like `TypeORM`). However, one could create a `getRepository()` function in the `QueryService` interface. What do you think about this?

All the best,
Johannes

**Comment by doug-martin** [comment]
@johannesschobel hello again! 

I would like to keep this out of the query service, I've tried to keep it generic enough to allow different implementations (typeorm, sequelize, etc) to be able to implement it. Once we introduce a repo that adds  another level of contracts.

Currently we only have typeorm, but as I'm finishing up the sequelize work I think this would be more difficult without having a common interface for a repository which isn't the case between the different ORMs. With sequelize its the "repo" is actually just static methods on the `Model` and typeorm they have a formalized `Repository` definition. 

With the `@InjectTypeOrmQueryService` or `@InjectSequelizeQueryService` I'm not sure how with the typescript type system we could ensure `getRepository` could return a value that is type safe.

If you have a suggestion on how to do that I'm all ears!

**Comment by johannesschobel** [comment]
Dear @doug-martin ,
yeah, i have already played around with this a bit in a local copy of this repo. And i could not get it to work to return a type safe `Repository`. The only thing that may work, would be to use generics - again, as you did across all the other services. One would need to type the `return repository` class..

this would be, of course, a breaking change, because you need to properly add those generics to the `database services`, and `assembler services` as well. This change would bubble up to the resolver classes, i guess.. so this would be a breaking change across all levels :worried:

**Comment by doug-martin** [comment]
I'm going to close this for now given conversation in other issues. If you come up with an easier way to integrate this OR better documentation to address this concern please issue a PR. 

I'll work on adding additional docs around this in the mean time!
