### ISSUE TITLE
[Improvement] Ability to override generated query/mutations names

### ISSUE THREAD

**Issue by Davide-Gheri** [doug-martin/nestjs-query#586]
I understood that the names of Queries and Mutations generated from CRUDResolver (and all other subsets of Resolvers) comes from the DTO name and the "plural" version is generated using `pluralize`. 

Thats ok for most of the cases, but sometimes plural is the same than singular (at least for pluralize), this causes the read one Query (`findById`) to be lost because it gets overridden by the read many Query (`getMany`). 
I see that there is a `dtoName` options but it does not help me.

For example, I have an ObjectType defined as `Agenda`, where singular and plural are both `agenda`, to make the read one endpoint work I had to create a custom Resolver that extends `ReadResolver` and override both `queryMany` and `findById` methods, define both `FindOneArgs` and `QueryArgs` (because they are not exposed outside the `Readable` mixin) and call the `getQueryManyHook` and `getFindOneHook` to keep hooks working.
I also lost the "dynamic" queryMany return type based on pagingStrategy.

It would be awesome to have an option to override single endpoint names.

**Comment by doug-martin** [comment]
@Davide-Gheri I'll take a look at this it shouldn't be too hard to add.

**Comment by doug-martin** [comment]
Hi @Davide-Gheri 

I published a new version `v0.21.1`. The new version allows you to specify a `one.name` or `many.name` option to override the auto-generated endpoint name. Checkout the [docs](https://doug-martin.github.io/nestjs-query/docs/graphql/resolvers/#override-endpoint-name) for an example.

Thank you for the feature request, and let me know if you have any issues!

-Doug
