### ISSUE TITLE
[Question / Feature Request] Support multi-tenants

### ISSUE THREAD

**Issue by ngdnghia28** [doug-martin/nestjs-query#604]
I follow [this guide](https://medium.com/@espositomarco.84/handle-multi-tenant-multi-db-with-nestjs-and-typeorm-ee50f162485e) to implement multi-tenants by using multi-databases.

But I cannot integrate it with these libs. Because your service class don't support nestjs REQUEST scope.

So could you show me the way to implement multi-tenants or do you have any plan to support this feature?

**Comment by doug-martin** [comment]
@ngdnghia28 I havent tried it but you could try creating a custom service following [these directions](https://doug-martin.github.io/nestjs-query/docs/persistence/typeorm/custom-service) and add the `@Injectable` decorator with the correct scope. You would also want to replace the `@InjectRepository` with the connection example found in the blog post, and pass in the repository from the connection. 


```ts
import { QueryService } from '@nestjs-query/core'
import { TypeOrmQueryService } from '@nestjs-query/query-typeorm';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, Connection } from 'typeorm';
import { TodoItemEntity } from './todo-item.entity';

@QueryService(TodoItemEntity)
@TenantService()
export class TodoItemService extends TypeOrmQueryService<TodoItemEntity> {
  constructor(
    @Inject(TENANT_CONNECTION) private connection: Connection,
  ) {
    super(this.connection.getRepository(TodoItemEntity));
  }
}
```

Hope this helps!

**Comment by ngdnghia28** [comment]
@doug-martin It worked.

Thank you.
