### ISSUE TITLE
make maxResultsSize and defaultResultSize optional

### ISSUE THREAD

**Issue by oldwolf** [doug-martin/nestjs-query#609]
Thanks for your awesome package. Sometimes I have to set a large number to maxResultsSize & defaultResultSize for some models, like countries or currencies, to query all the data, this works but maybe there's better way to deal with?

Also there is inconsistent naming for maxResultSize, below is quoted from documentation
> Default Paging#
> By default all results will be limited to 10 records, with a max of 50 records returned.
> 
> To override the default you can override the following options:
> 
> read.defaultResultSize - The default number of results to return.
> **read.maxResultSize** - The maximum number of results an end user can specify to return.
> In this example we specify the defaultResultSize to 5 and **maxResultsSize** to 20.

**Comment by doug-martin** [comment]
@oldwolf in this case would it be better to turn paging off for those models? https://doug-martin.github.io/nestjs-query/docs/graphql/paging#disabling-paging

**Comment by oldwolf** [comment]
Yeah, i had same consideration before, but sometimes we need paging for listing page, while for dropdown selection or CSV export we want to disable paging, is there a way to kill two birds with one stone?

**Comment by doug-martin** [comment]
@oldwolf there isn't a way to make a relation act in different ways based on the use case. You could add the same relation twice one version for paging the other where the paging is turned off, but that could be confusing.

What is your suggestion on how to address this issue?

**Comment by oldwolf** [comment]
i would suggest remain the default result size & max result size, while adding an option to override them, like noLimitSize: true

**Comment by doug-martin** [comment]
Added the ability to set `-1` on `maxResultSize` to disable limiting of page sizes.
