### ISSUE TITLE
"Page not found" in docs for TypeOrmQueryService

### ISSUE THREAD

**Issue by amille14** [doug-martin/nestjs-query#61]
Several places in the docs refer to the TypeOrmQueryService docs and link to the following page:
https://doug-martin.github.io/nestjs-query/docs/typeorm/getting-started/services

This seems to be a broken link, not sure where the actual docs for TypeOrmQueryService live now.

**Comment by doug-martin** [comment]
Thanks for pointing that out...feel free to open a PR to fix.

Otherwise Ill try to get to that tonight.

The service documentation is now located in the [`usage doc`](https://doug-martin.github.io/nestjs-query/docs/typeorm/usage#creating-a-service)

**Comment by doug-martin** [comment]
This turned out to a a couple of issues.
1. A docusaurus bug, upgrading fixed.
2. A couple of wrong links.

Thanks again for reporting!
