### ISSUE TITLE
It's guard and ResolveProperty still work?

### ISSUE THREAD

**Issue by zerox12311** [doug-martin/nestjs-query#69]
I tried @ResolveProperty and guard , but I found it doesn't work any more.
I just follow document getting started and then add it.
I had add **fieldResolverEnhancers: ['guards', 'interceptors'],** in GraphQLModule.
Is me miss anything?

**Comment by johannesschobel** [comment]
Dear @zerox12311 ,

note that this package now requires `NestJS 7.x` under the hood. The most important change from Nest6 -> Nest7 are all within the `graphql` package. This package now provides the `code-first` approach, that was previously provided by the 3rd party package `type-graphql`.

Nest7, however, renamed the `@ResolveProperty()` decorator. It is now called `@ResolveField()` i guess!

All the best
