### ISSUE TITLE
Error: Schema must contain uniquely named types but contains multiple types

### ISSUE THREAD

**Issue by vabatta** [doug-martin/nestjs-query#700]
**Describe the bug**
By following the example available at https://github.com/doug-martin/nestjs-query/tree/master/examples/federation, the following error is thrown when running `sub-task-graphql`.

```
UnhandledPromiseRejectionWarning: Error: Schema must contain uniquely named types but contains multiple types named "SubTask".
```

**To Reproduce**
1. Run locally the example
2. Run the `sub-task-graphql`

**Expected behavior**
To have Federation working properly when extending remote ObejctTypes.

**Desktop (please complete the following information):**
 - Node Verson [e.g. 14.14.0] 14
 - Nestjs-query Version [e.g. v0.21.0] latest

**Comment by onichandame** [comment]
@vabatta I am seeing the same error. Could you share how it was fixed for you?

**Comment by thehappycoder** [comment]
@onichandame I got it too but in my project. I solved it by renaming the file of my DTO, saving it and saving all other files that depended on it. Magic but it worked 2 times for me at different days (2 different DTOs)!

My error was:
Error: Schema must contain uniquely named types but contains multiple types named "Breed"
