### ISSUE TITLE
[Question]: Filter By Relationships

### ISSUE THREAD

**Issue by johannesschobel** [doug-martin/nestjs-query#71]
Dear @doug-martin ,

once again - I have a question regarding the use of your library.
Consider the following example:

I have three Entities, which are linked. One `Person` has written many `Post`s, one `Post` belongs to one `Board`. Likewise, a `Board` contains many `Post`s, one `Post` belongs to one `Person`. The relationships are all set up via `TypeOrm` via `@ManyToOne()`. Furthermore, i have dedicated `@RelationId()` decorators to get the plain value of the referenced id.

Now i would like to create a new Custom Resolver function, which is called `getPostsByPersonInBoard` (awesome name, i know!)

Therefore, i followed the docs on your site, and did the following:
- Create a new `ConnectionType`:
```ts
// custom.types.ts
export const PostConnection = ConnectionType(PostObject);
```

- Create a new `ArgsType()` for this `@Query()`
```ts
// custom.types.ts
@ArgsType()
export class GetPostsByPersonAndBoardArgsType extends QueryArgsType(
  PostObject,
) {
  @IsString()
  @IsUUID('4')
  @Field()
  boardId: string;

  @IsString()
  @IsUUID('4')
  @Field()
  personId: string;
}
```

Following these 2 steps, I create the "request and response types" for this query.

- Create the custom resolver function
Finally, i create my custom resolver function like this:
```ts
  @Query((returns) => PostConnection, {
    name: 'getPostsForPersonAndBoard',
  })
  async getPostsForPersonAndBoard(
    @Args() query: GetPostsByPersonAndBoardArgsType,
  ) {

    const posts = await this.postsDatabaseService.query({
      paging: query.paging,
      sorting: query.sorting,
      filter: {
        // <-- what do i do here?!
      },
    });

    const transformedPosts = this.service.assembler.convertToDTOs(posts);

    return ScreeningConnection.createFromArray(
      transformedPosts,
      query.paging || {},
    );
  }
```

The problem is, that i need to build a `filter` that allows me to query for these 2 particular relationships that are passed within the `query.boardId` and `query.personId` respectively.

Problem is, that none of my approaches worked so far. What i tried was to create a filter like this:
```
filter: {
  personId: { eq: query.personId },
  // ...
}
```

This fails because there is no property `PostEntity.personId`. Respective relationship is called `PostEntity.person` (relationship) or `PostEntity._personId` (for the `@RelationshipId()` field). Changing the filter to use `person` or `_personId` has not worked so far for me either.

How can i achieve my goal?
Thank you very much for your kind help!

All the best

**Comment by johannesschobel** [comment]
Okaaaaaaaaaaaaaaaaay... i think, i found a solution..
Setting the filter like this works:
```ts
filter: {
  'person.id': { eq: query.personId },
  'board.id' : { eq: query.boardId },
}
```

However, the IDE throws errors like this:
```bash
Type '{ 'person.id': { eq: string; }; 'board.id': { eq: string; }; }' is not 
assignable to type 'Filter<PostEntity>'.
  Object literal may only specify known properties, and ''person.id'' does 
  not exist in type 'Filter<PostEntity>'.
query.inteface.d.ts(36, 5): The expected type comes from property 'filter' 
which is declared here on type 'Query<PostEntity>'
```

This is a dirty hack, and may not be intended to work. However, i read in the docs, that the `filter` is directly translated to a `TypeOrm` `where`-clause. In `TypeOrm` you may do it like this:

```ts
where: {
  person: {
    id: query.personId
  },
  // ...
}
```

Maybe you can guide me to the proper approach?

All the best

**Comment by doug-martin** [comment]
@johannesschobel I would create a custom method in my service that calls the repo directly to translate query.
