### ISSUE TITLE
[Bug]: Defining additional UpdateDtos breaks Schema

### ISSUE THREAD

**Issue by johannesschobel** [doug-martin/nestjs-query#72]
Dear @doug-martin ,

while working on custom resolver methods, i stumbled upon an issue, i was able to reproduce in your example repository (shipped in this library).

You can take a look at the "how to reproduce" by looking at my commits here

### https://github.com/doug-martin/nestjs-query/compare/master...johannesschobel:issue/update-dto

# Description
I wanted to add a dedicated `completeTodoItem` mutation that only takes the `completed` parameter. Note that the original `updateTodoItem` also takes the `name`, and `completed` was set to `optional`. The dedicated `completeTodoItem` mutation should take this parameter as required.

- I created a new `Input DTO` in order to provide sophisticated validations
- I created a new `InputType()` that uses this dto
- I created a new `Mutation` in my `Resolver` that uses this newly created `InputType`.

Note that i also committed the initial `schema.gql` file to see the actual changes in this file!

As you can see, the new mutation is added correctly. Also, the newly created `InputType` as well as the `dto` are added correctly. **However**, the `dto` for the regular `UpdateOneTodoItem` **is also changed** to this newly created `dto` - which is, obviously, wrong.

I hope you can reproduce the issue? Maybe i am doing something wrong here? As the docs were not quite accurate in this point, i was not sure if my approach is correct. I would be willing to document this feature, if we can figure out how to deal with the latter?

All the best and thanks for your time!

**Comment by doug-martin** [comment]
Yep, I see the issue.

In https://github.com/doug-martin/nestjs-query/blob/master/packages/query-graphql/src/types/update-one-input.type.ts#L23 we set the `InputType` name. I think the fix would be to update it to be abstract and let the implementing code specify the `InputType` name.

This would apply for all the create, update and delete types. Ill try to take a look at this over the next couple of days unless you want to tackle it.

**Comment by johannesschobel** [comment]
Dear @doug-martin ,

thanks for confirming this bug. Glad i did nothing wrong here :smile: 

Basically, you would change it to something liket his, right?
```diff
@InputType()
export class CompleteTodoItemInputType extends UpdateOneInputType(
+ 'CompleteTodoItemInput',
  TodoItemDTO, 
  CompleteTodoItemDTO
) {}
```

Am I correct?
All the best,
Johannes

**Comment by doug-martin** [comment]
@johannesschobel I'm working on this now.

It looks like its going to be updated to

```ts
@InputType()
export class CompleteTodoItemInputType extends UpdateOneInputType(
  TodoItemDTO, 
  CompleteTodoItemDTO
) {}
```

and the `UpdateOneInputType` will be changed to 

```diff
export function UpdateOneInputType<DTO, U extends DeepPartial<DTO>>(
  DTOClass: Class<DTO>,
  UpdateType: Class<U>,
): Class<UpdateOneInputType<DTO, U>> {
  const metadataStorage = getMetadataStorage();
  const existing = metadataStorage.getUpdateOneInputType<DTO, U>(DTOClass);
  if (existing) {
    return existing;
  }
  const { baseName } = getDTONames(DTOClass);
-  @InputType(`UpdateOne${baseName}Input`)
+  @InputType({ isAbstract: true })
  class UpdateOneInput implements UpdateOneInputType<DTO, U> {
    @IsNotEmpty()
    @Field(() => ID, { description: 'The id of the record to update' })
    id!: string | number;

    @Type(() => UpdateType)
    @ValidateNested()
    @Field(() => UpdateType, { description: 'The update to apply.' })
    update!: U;
  }
  metadataStorage.addUpdateOneInputType(DTOClass, UpdateOneInput);
  return UpdateOneInput;
}

```

**Comment by doug-martin** [comment]
@johannesschobel I've pushed up my changes to https://github.com/doug-martin/nestjs-query/tree/issue72 I'll finish cleaning up the docs and stuff tomorrow. 

I ended up changing the the `UpdateOneInputType` method to the following

```ts
export function UpdateOneInputType<U>(UpdateType: Class<U>): Class<UpdateOneInputType<U>> {
  @InputType({ isAbstract: true })
  class UpdateOneInput implements UpdateOneInputType<U> {
    @IsNotEmpty()
    @Field(() => ID, { description: 'The id of the record to update' })
    id!: string | number;

    @Type(() => UpdateType)
    @ValidateNested()
    @Field(() => UpdateType, { description: 'The update to apply.' })
    update!: U;
  }
  return UpdateOneInput;
}
```

Once I publish you should be able to just extend the type like so

```ts
@InputType()
export class CompleteTodoItemInputType extends UpdateOneInputType( CompleteTodoItemDTO) {}
```
And the graphql type will be named `CompleteTodoItemInputType`. 

Let me know what you think and if I should make any additional changes.

Stay safe and healthy!

-Doug

**Comment by johannesschobel** [comment]
Dear @doug-martin ,
thanks for sharing your thoughts on this and discussing the further roadmap with me!
Actually, i like the idea of just creating it as an `abstract` class! For the "dummy" implementation (i.e., no custom type was defined), the abstract class is extended with no particular changes, right?

So basically - for the developer using your awesome library, nothing changes ;)

All the best and stay safe,
Johannes

**Comment by doug-martin** [comment]
This is published under `v0.8.0` I had to make breaking changes to the create and update input types, since the no longer required the "base" dto. 

So your update type would change from
```ts
@InputType()
export class CompleteTodoItemInputType extends UpdateOneInputType(TodoItemDTO, CompleteTodoItemDTO) {}
```
To 
```ts
@InputType()
export class CompleteTodoItemInputType extends UpdateOneInputType(CompleteTodoItemDTO) {}
```

Small change but still breaking. You can checkout the [types](https://doug-martin.github.io/nestjs-query/docs/graphql/types) documentation for more info.

Thanks again for the bug report!

**Comment by johannesschobel** [comment]
Dear @doug-martin 
thank you very much for the new release.
The time needed to adapt to the latest changes will be minimal - thank you for keeping the public API so clean and slim! Very much appreciated!

Can you please release the new version on npm? It has been tagged on GitHub but not released on NPM so far..

All the best and thank you very much for your time and effort working on this library!

**Comment by doug-martin** [comment]
Sorry about that its published!

**Comment by johannesschobel** [comment]
you are awesome.. happy eastern - wish you all the best!
will try to update the lib next week!
