### ISSUE TITLE
[Suggestion] Maybe can add more entry point to service to supply override

### ISSUE THREAD

**Issue by zerox12311** [doug-martin/nestjs-query#76]
I think it can supply like **preCreate** method in ** TypeOrmQueryService** class, then I need to modify data before insert , I can override it and I don't need to override all createOne method.
This suggestion is from [django rest framework ModelViewSet](https://github.com/encode/django-rest-framework/blob/master/rest_framework/mixins.py#L23:1).
How do you think about it?

Like: 
```javascript
  async createOne<C extends DeepPartial<Entity>>(record: C): Promise<Entity> {
    await this.ensureEntityDoesNotExist(record);
    return this.repo.save(record);
    return this.preCreate(record);
  }

  async preCreate(record) {
      return this.repo.save(record)
  }
```

**Comment by doug-martin** [comment]
@zerox12311 this library isnt intended to replace an orm, instead I would take a look at https://typeorm.io/#/listeners-and-subscribers/what-is-an-entity-listener for examples on different model hooks.

**Comment by zerox12311** [comment]
@doug-martin I know this library isn't intended to replace orm.
Entity Listener just handle one entity action, If had more entry point in service layer, I can do more complex thing like query another entity or with my logic.
For example I have an entity with user field, I want to add this field automatic in my logic, so I need to query user table with some logic and insert it in backend.

**Comment by johannesschobel** [comment]
Dear @zerox12311 ,
yeah, but you could also extend the `UserDatabaseService` that is automatically generated by this library and then overwrite the `createOne()` method (for example).

Within this method, you just call the `super.createOne()` method (from the extended class) and add your logic before / after this call. That would be another possibility..

Hope this helps
