### ISSUE TITLE
query pageinfo error when mocks enbaled

### ISSUE THREAD

**Issue by Diluka** [doug-martin/nestjs-query#774]
**Describe the bug**
`Error: No mock defined for type "ConnectionCursor"`

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

**To Reproduce**
1. mocks: true
2. mockEntireSchema: false

**Expected behavior**
no errors

**Screenshots**

**Desktop (please complete the following information):**
 - Node Verson [e.g. 14.14.0]
 - Nestjs-query Version [e.g. v0.21.0]

**Additional context**

**Comment by doug-martin** [comment]
@Diluka I need more information :) Can you please provide an example spec?

**Comment by Diluka** [comment]
https://codesandbox.io/s/nestjs-query-issues-774-bhcrm?file=/README.md

it seems not relate to `nestjs-query` but `graphql-scalars`.
