### ISSUE TITLE
Virtual Fields

### ISSUE THREAD

**Issue by steinroe** [doug-martin/nestjs-query#782]
Hi,

again, I think this library is highly underrated - such great work!

**Is your feature request related to a problem? Please describe.**
I have the following setup (minimised):

UserDTO:
```
@ObjectType('User')
export class UserDTO {
  @FilterableField(() => ID)
  id!: string;

  @FilterableField(() => GraphQLISODateTime)
  createdAt!: Date;

  @FilterableField(() => GraphQLISODateTime)
  updatedAt!: Date;

  @FilterableField()
  email!: string;

  @FilterableField()
  emailVerified!: boolean;
```

User Entity:
```
@Entity('User')
export class UserEntity {
  @PrimaryColumn()
  id!: string;

  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;

  @Column()
  email!: string;
}
```

I now want to return the emailVerified field based on the current user, because I retrieve the auth info for that user form a third party service. Normally, I would simply do this in the UserResolver:

```
@ResolveField('emailVerified', returns => GraphQLBoolean)
  async emailVerified(@CurrentUser() currentUser: AuthUser): Promise<boolean> {
    return currentUser.emailVerified;
  }
```
but the custom resolver is invalid due to the missing emailVerified field in the entity. It would be great if we would have a "virtual fields" option, similar to the virtual relations.

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?

Yes.

**Describe the solution you'd like**
It would be great if there would be a virtual field option, similar to the virtual relations.

**Describe alternatives you've considered**
Another option would be to leverage the write and update hooks to keep the email verified field in sync with the email verified value from the the third party service. This is a very valid option, but I think virtual fields would be a great addition to this awesome package. :) 
Another option I thought about was to allow access to the current user (e.g. using decorators) within an assembler, but I don't know whether that is possible / valid.

What do you think?

Thanks!

**Comment by smolinari** [comment]
@steinroe - Why did you close this?

Scott

**Comment by steinroe** [comment]
Hi @smolinari ,

sorry for leaving this uncommented!

Achieving the desired behaviour is already possible by simply removing the field from the DTO and adding a named FieldResolver to the resolver:

```
@ObjectType('User')
export class UserDTO {
  @FilterableField(() => ID)
  id!: string;

  @FilterableField(() => GraphQLISODateTime)
  createdAt!: Date;

  @FilterableField(() => GraphQLISODateTime)
  updatedAt!: Date;

  @FilterableField()
  email!: string;

  @FilterableField()
  emailVerified!: boolean;
}
```

```
@Resolver(() => UserDTO)
export class UserResolver extends CRUDResolver(UserDTO) {
  constructor(readonly service: UserService) {
    super(service);
  }

  @ResolveField('emailVerified', returns => GraphQLBoolean)
  async emailVerified(@CurrentUser() currentUser: AuthUser): Promise<boolean> {
    return currentUser.emailVerified;
  }
}
```

Thanks for asking!
Best
Philipp
