### ISSUE TITLE
[Suggestion] Update many input as array

### ISSUE THREAD

**Issue by praaxe** [doug-martin/nestjs-query#79]
Hello @doug-martin,

We are still using your awesome library but today we hit a wall with multiple update.
Let's say we want for an entity to set all entities with an id below 10 to status A, all entites with id between 10 and 20 to status B, etc.

The only we to do it we found was to make multiple call since updateMany does not take an array as input and we can't call multiple time the same mutation.

Wouldn't it be better for updateMany functions to accept arrays of updateManyXXInput instead of just one ?

**Comment by praaxe** [comment]
It seems that we have the same issues with ManyToMany relations and the addXXXToYYY mutation.

I don't know if this can be done easily but that would be awesomer than it actually is =D

**Comment by doug-martin** [comment]
Hi @praaxe 

I'm hesitant to change this in the resolvers, you can still make.

You could try something like the following to do it in one request

```graphql 
mutation {
 updateLtTen: updateManyTodoItems(
   input: { filter: { id: { lte: 10 } }, update: { completed: true } }
 ) {
   updatedCount
 }
 updateGtTen: updateManyTodoItems(
   input: {
     filter: { and: [{ id: { gt: 10 } }, { id: { lt: 20 } }] }
     update: { completed: false }
   }
 ) {
   updatedCount
 }
}

```

**Comment by praaxe** [comment]
oh !
I didn't know we could use aliases !

This is indeed a nice solution to our issue. Thanks for the tip.
