### ISSUE TITLE
enableTotalCount with Offset paging strategy

### ISSUE THREAD

**Issue by thehappycoder** [doug-martin/nestjs-query#790]
With offset paging strategy enabled, I also need to know the total number of nodes, so that I could calculate the number of available pages on the client side.

**Comment by incode4it** [comment]
Really a must-have feature.
I solved this by overriding the default query method.

```
@ArgsType()
export class ItemQuery extends QueryArgsType(
  ProductDto,{
    pagingStrategy: PagingStrategies.OFFSET,
    defaultSort: [{field: 'createdAt', direction: SortDirection.DESC}],
  }) {

@ObjectType('ProductsWithCount')
export class ProductsWithCount {
  @Field()
  count: number;

  @Field(() => [ProductDto])
  nodes: ProductDto[]
}

@Resolver(() => ProductDto)
export class ProductResolver extends CRUDResolver(ProductDto, {
  pagingStrategy: PagingStrategies.OFFSET,
  enableAggregate: true,
  read: {
    many: {
      disabled: true
    }
  },
}) {
  constructor(
    @InjectQueryService(ProductEntity) readonly productEntityQueryService: QueryService<ProductEntity>,
  ) {
    super(productEntityQueryService as any);
  }

  @Query(() => ProductsWithCount)
  public async products(
    @Args() query: ItemQuery,
    @Context() context: any
  ) {
    const count = await this.service.count(query.filter as any);
    const records = await this.queryMany(query);
    return {count, nodes: records};
  }
}

```

**Comment by jfrader** [comment]
I'm really blocked by this one, is there a plan to implement this?

**Comment by yeomann** [comment]
is there update, really needed feature. we have aggregation but aggregation on relation doesn't work. its a sad situation

**Comment by doug-martin** [comment]
I'm starting to look into this, I really think the best approach is to change offset based paging to return a connection object that looks like the following

```ts
interface OffsetConnection {
  nodes: DTO[];
  totalCount?: number;
  pageInfo: { hasNextPage: boolean, hasPreviousPage: boolean}
```

This will be a breaking change for people currently using offset, but I think is worth it to create a more consistent experience when enabling certain features, and will be more extensible in the future.

**Comment by doug-martin** [comment]
I just release the latest version (v0.23.0) that includes the changes discussed. Checkout out the [release notes](https://github.com/doug-martin/nestjs-query/discussions/911) and the [paging docs](https://doug-martin.github.io/nestjs-query/docs/graphql/paging#offset-based-paging) for complete examples!

Thank you to everyone for you input and support!
