### ISSUE TITLE
Connecting to websocket

### ISSUE THREAD

**Issue by tillsanders** [doug-martin/nestjs-query#793]
I have trouble connecting from my Nuxt Apollo module / vue-apollo to the websocket endpoint. I followed the documentation and enabled the endpoint with the `enableSubscriptions` options. Since there is no URL specified either in the nest.js docs nor the nestjs-query docs (maybe that could be improved?), I'm guessing. I get the following results:

- ws://localhost:3000: `ERROR: WebSocket connection to 'ws://localhost:3000/' failed: Error during WebSocket handshake: Unexpected response code: 200`
- ws://localhost:3000/graphql: `ERROR: WebSocket connection to 'ws://localhost:3000/graphql' failed: Error during WebSocket handshake: Unexpected response code: 400`
- ws:://localhost:3000/subscriptions: `WARNING: WebSocket connection to 'ws://localhost:3000/subscriptions' failed: WebSocket is closed before the connection is established.`

Judging from these messages and some issues I've found, I'm guessing the last url is correct. If that is the case though, I have no idea, what the underlying problem is. My graph is generated correctly and works so far. Only the websocket endpoint troubles me. 

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?

Yes

**To Reproduce**

Since I'm only activating the endpoint using the `enableSubscriptions` option and setting the `wsEndpoint` option of vue-apollo, there isn't much code to show. I guess, I'm falling for a beginner mistake?

**Desktop (please complete the following information):**
 - Node Version 12.16
 - Nestjs-query Version 0.21.2

**Comment by tillsanders** [comment]
Side note: I feel like this is not really a bug report. Maybe we could enable the new Discussions feature for this repository so we can ask questions there? 🙂

**Comment by smolinari** [comment]
@tillsanders - Maybe a silly question, but did you turn on subscriptions within NestJS' GraphQL Module?

https://docs.nestjs.com/graphql/subscriptions#enable-subscriptions

Scott

**Comment by tillsanders** [comment]
@smolinari I'm pretty stuck, so at this point, there are no silly questions 😄  I didn't, in fact turn that on. Somehow, I was under the impression, that this would be handled by nestjs-query. Unfortunately, I still get an error message: 

```
WebSocket connection to 'ws://localhost:3000/subscriptions' failed: Error during WebSocket handshake: Unexpected response code: 400
```

**Comment by smolinari** [comment]
Unfortunately, I have little experience with subscriptions. Hope someone else can chime in. 

Scott

**Comment by doug-martin** [comment]
@tillsanders I added basic support for them based on other feature requests, however we don't really use them in our application because we are using federation :( I'll need to research this more but that will be a couple of days after I wrap up the custom operator work.

**Comment by tillsanders** [comment]
Hey Scott,
thanks for your continuous support on this matter! I now have subscriptions working! 

I'm not completely sure, why it didn't work before. Maybe it was a caching problem or something. I activated the options described above and could get subscriptions to work with the GraphQL Playground. My apollo configuration in Nuxt.js now looks like this: 

```javascript
// nuxt.config.js
  apollo: {
    clientConfigs: {
      default: {
        httpEndpoint: 'http://localhost:3000/graphql',
        wsEndpoint: 'ws://localhost:3000/graphql', // ← working now
      },
    },
  },
```

**Comment by tillsanders** [comment]
@doug-martin Thanks for your reply!
I'm not very familiar with federations. In what way can they be a substitute for subscriptions?

I got subscriptions working with vue-apollo now, but the solution is not exactly elegant and I'm not sure why. I'm following the documentation of vue-apollo here: https://apollo.vuejs.org/guide/apollo/subscriptions.html#simple-subscription. The idea is, that I fetch a list of objects using a `query` and then I subscribe (subscribeToMore) to the `created` event of nestjs-query to get new objects upon creation. The problem is, that the initial `query` and the `subscription` yield slightly different formats. The `query` of many objects will return edges, pageInfo and so on. The `subscription` simply returns the object itself. I would say that this makes sense for nestjs-query. But unfortunately, vue-apollo expects the same format for both. So, I can "fake" this format and make it work, but that's not exactly an elegant solution. Do you have any idea, what could be done about this? Is it my problem, or a problem of vue-apollo, or nestjs-query, or maybe just GraphQL in general? Is there any convention for this?

**Comment by smolinari** [comment]
> I'm not very familiar with federations. In what way can they be a substitute for subscriptions?

It's not a substitute, subscriptions don't yet work with federation. 

Scott

**Comment by tillsanders** [comment]
Ahh, I see 😄

**Comment by doug-martin** [comment]
@tillsanders I have not seen a convention for subscriptions, but then again I haven't used them a whole lot. If you can find a convention with a spec that should be followed we could look at either adding an option to support it or change all of the subscriptions to follow the convention. 

Thank you for the updates, I'm glad you were able to get it working!
