### ISSUE TITLE
Allow class-validator options to be set

### ISSUE THREAD

**Issue by steinroe** [doug-martin/nestjs-query#801]
Hi,

it would be really great if we could allow class-validator options to be set. This would help anyone who is not using the default options in the global validation pipe. 

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?

Yes

**Describe the solution you'd like**
It would be great to have the possibility to pass class validator options to nestjs-query to be used in the transformAndValidate helper.

```
// /query-graphql/src/resolvers/helpers.ts 
/** @internal */
export const transformAndValidate = async <T>(TClass: Class<T>, partial: T, validatorOptions: ValidatorOptions): Promise<T> => {
  if (partial instanceof TClass) {
    return partial;
  }
  const transformed = plainToClass(TClass, partial);
  const validationErrors = await validate(transformed, validatorOptions);
  if (validationErrors.length) {
    throw new BadRequestException(validationErrors);
  }
  return transformed;
};
```

**Describe alternatives you've considered**
An alternative is to just use the default settings in the global validation pipe, and this is fine. But I think it would allow greater freedom if that would be possible.

What do you think about this?

**Comment by smolinari** [comment]
@steinroe - Would creating your own validation pipe help with this? 

https://doug-martin.github.io/nestjs-query/docs/graphql/resolvers#guards-pipes-filters-and-interceptors

I was trying to get a custom pipe done to use class-validator's schema and was successful up to the point of using the `validate` method, but for some reason the schema is ignored and `validate` always returns an empty array. But for sure I could set the options as I needed. 

Scott

**Comment by steinroe** [comment]
Hi @smolinari, thanks for the quick reply. Also thanks for pointing me to this great library - it saved us weeks!

I don't think that suits our needs. We have defined a global validation pipe with useGlobalPipe and use non-default settings there (we want to skip missing values).

In the implementation however calls class-transformer manually in the resolver:
```
@Resolver(() => DTOClass, { isAbstract: true })
  class UpdateResolverBase extends BaseClass {
    @ResolverMutation(() => DTOClass, { name: updateOneMutationName }, commonResolverOpts, opts.one ?? {})
    async updateOne(@MutationArgs(UO, updateOneHook) input: UO, @Context() context?: unknown): Promise<DTO> {
      const updateOne = await transformAndValidate(UO, input); // <-- here the helper is called
      const authorizeFilter = await getAuthFilter(this.authorizer, context);
      const { id, update } = updateOne.input;
      const updateResult = await this.service.updateOne(id, update, { filter: authorizeFilter });
      if (enableOneSubscriptions) {
        await this.publishUpdatedOneEvent(updateResult);
      }
      return updateResult;
    }
```

```
/** @internal */
export const transformAndValidate = async <T>(TClass: Class<T>, partial: T): Promise<T> => {
  if (partial instanceof TClass) {
    return partial;
  }
  const transformed = plainToClass(TClass, partial);
  const validationErrors = await validate(transformed, {}); // <-- which validates with default options
  if (validationErrors.length) {
    throw new BadRequestException(validationErrors);
  }
  return transformed;
};
```

This means that no matter how the pipes look like, class-validator will always be applied by query-nestjs with default options.

However, let me know if I miss something here!

**Comment by smolinari** [comment]
Shouldn't the global pipe override anything nestjs-query is doing? In other words, the request should fail before the resolver is even hit?

Scott

**Comment by doug-martin** [comment]
@smolinari @steinroe This may be addressed in later versions of `@nestjs/graphql` but when initially implementing the library the transform and validation logic was not always applied so I added it to the resolver to ensure the resolver always had an instance of the DTO that had been validated. 

Because the global validation pipe is applied before all other pipes `nests-query` effectively ignores the options. I'll need to look into this more to see if we can remove this code path entirely, if not it may make sense to allow specifying validation options to the resolver.

**Comment by doug-martin** [comment]
The validate has been removed in the latest versions of `nestjs-query`. Thanks for submitting an issue!
