### ISSUE TITLE
[Feat]: RESTful Controllers

### ISSUE THREAD

**Issue by johannesschobel** [doug-martin/nestjs-query#804]
Dear @doug-martin ,

long time no hear ;) Was quite busy the last months, but i am kicking off a new project in a few months. As i used your library in my last project, i would like to use this library again - as it is **super** convenient to use!

**Is your feature request related to a problem? Please describe.**
However, based on specific requirements, i would need to build a RESTful application, as clients (3rd party integrators) can only use RESTful calls and are not able to use GraphQL.

Therefore, i am asking, if we could develop a `@nestjs-query/rest` package in order to provide the required functionality. What do you think?

All the best and stay healthy,
Johannes

**Comment by johannesschobel** [comment]
Dear @doug-martin ,
hooking into this issue again.. I just looked into this - basically, how we could achieve such a functionality..
Basically, the `nestjs-query/typeorm` package provides independent logic and can be reused 100%, i guess.

Maybe we would need to create a new `nestjs-query/rest` package, that is able to create `controllers` based on decorators - similar to the `nestjs-query/graphql` package.

Same applies to the `assemblers` as well. Because the `ObjectTypes` have respective `GraphQL Decorators`, we would need to have something similar for the `rest world`. I propose to name them `transformers` - however, the latter are annotated with `Swagger` decorators to be able to generate docs automatically.

What do you think?

**Comment by doug-martin** [comment]
Hi @johannesschobel!

I'm not opposed to this I think we could reuse the query services entirely, but would need parallels for the different decorators `FilterableField` relations etc.

I do wonder how much of that we could keep transparent, so you could have the same DTO definitions and the module import would determine how it is exposed rest, GraphQL or both. This may be pretty invasive but could lead to a pleasant user experience.

I don't currently have the bandwidth to start on this but if you want to start diving in go for it!

**Comment by johannesschobel** [comment]
Dear @doug-martin ,
thank you very much for the answers and respective ideas. I will see what i can do. Maybe it will work out ;)
All the best,
Johannes
