### ISSUE TITLE
Keep relation after soft delete with sequalize

### ISSUE THREAD

**Issue by ledamint** [doug-martin/nestjs-query#808]
Hi
I use Sequalize-typescript and Postgres DB. 
I have in a model:
```
@DeletedAt
deleted: Date;
```
So DB doesn't delete an entity, just add deleted time in `deleted` after the call GraphQL delete method.
All is ok but I have a relation to this deleted entity and I want to continue to get info about the deleted entity through a related entity but now I get an error.

Example:
I have a client
```ts
@Table
export class Client extends Model {
   // ...
  @DeletedAt
  deleted: Date;
```
and a visit
```ts
@Table
export class Visit extends Model {
   // ...
  @ForeignKey(() => Client)
  @Column({ allowNull: false })
  client_id: number;

  @BelongsTo(() => Client)
  client: Client;
```
I create a visit with an existed client
```
createOneVisit(
    input: {
      client_id: 1
```
After this, I delete the client and try to get a visit but I get an error because a client is null, but the information about the client is in DB. How  can fix it?

**Comment by doug-martin** [comment]
@ledamint this is an odd use case, I'm curious why are you using soft deletes if you still want to fetch information about it, would a boolean flag work better in this case so you could filter on that value? 

If you can provide your graphql query that's failing it may help me to understand the use case a little better.

**Comment by ledamint** [comment]
I have already done the boolean flag, thank you. About this issue maybe it's good to add an opportunity to allow to use get soft-deleted entities with get request because orm has this functionality

**Comment by doug-martin** [comment]
@ledamint I'm having a hard time seeing how to implement this generically to make it useful for something other than a specific use case. I'm not saying its not a useful feature (we don't uses soft deletes internally) but if you could provide a couple of examples of how you one would use this option it will help in determining if this should or should not be added to the framework.

Thank you for using the nests-query and your feedback!
