### ISSUE TITLE
Expecting DTO instead of Entity

### ISSUE THREAD

**Issue by coder2000** [doug-martin/nestjs-query#81]
I have a couple of resolvers that are not working as they are expecting the QueryService to be for the DTO and not the entity class. Is this normal?

One of the resolvers is for the podcast and you can view the code at https://github.com/coder2000/speakrr/blob/master/packages/server/src/modules/podcast/podcast.resolver.ts

**Comment by amille14** [comment]
I ran into the same issue. I ended up just making my DTO and Entity classes the same class and its working. Not ideal if you'd rather keep them separate.

**Comment by coder2000** [comment]
I had them as the same class originally, however, due to the relationships I was getting errors about being unable to find input classes.

**Comment by coder2000** [comment]
Thank you for your assistance on the NestJS discord server.
