### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by ridyio** [doug-martin/nestjs-query#854]
**Describe the bug**
Apollo server prior to v3 has support for multipart upload through GraphQLUpload field type. If this field type is assigned in DTO class when i try to upload a file i get this error which traces back to nesjs-query so it seems. Has anyone been able to use file upload with nestjs-query.

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?
Yes

**To Reproduce**
1-Create a resolver and DTO classes. Set a field decorator with type GraphQLUpload (imported from apollo-server-express)
2-Send a request with file logo.jpg
```
curl --location --request POST 'http://localhost:3000/graphql' \
--form 'operations={ "query": "mutation ($file:Upload!) { updateOneAgent(input: { id:1, update: { image:$file } }) { id } }", "variables": { "file": null } }' \
--form 'map={ "0": ["variables.file"] }' \
--form '0=@logo.jpg'
```

**Expected behavior**
Not an error:
```
Promise resolver undefined is not a function
    at new Promise (<anonymous>)
    at TransformOperationExecutor.transform (./node_modules/class-transformer/cjs/TransformOperationExecutor.js:128:32)
    at TransformOperationExecutor.transform (./node_modules/class-transformer/cjs/TransformOperationExecutor.js:267:47)
    at TransformOperationExecutor.transform (./node_modules/class-transformer/cjs/TransformOperationExecutor.js:267:47)
    at TransformOperationExecutor.transform (./node_modules/class-transformer/cjs/TransformOperationExecutor.js:267:47)
    at ClassTransformer.plainToClass (./node_modules/class-transformer/cjs/ClassTransformer.js:17:25)
    at Object.plainToClass (./node_modules/class-transformer/cjs/index.js:30:29)
    at Object.exports.transformAndValidate (./node_modules/@nestjs-query/query-graphql/dist/src/resolvers/helpers.js:13:45)
    at ./node_modules/@nestjs-query/query-graphql/dist/src/decorators/hook-args.decorator.js:11:38
    at ./node_modules/@nestjs/core/helpers/context-utils.js:36:28

```

**Desktop (please complete the following information):**
 - Node Verson 15.3.0
 - Nestjs-query Version 0.21.2

**Additional context**
I understand there are some processing needs to be done with uploading file but i am not clear on how they need to be done. I tried writing a FieldMiddleware on field to be able to do the write of file and return address of file then save into db but this error occurs before middleware is called.

**Comment by luca-nardelli** [comment]
Hey, unfortunately I can't help you directly with your error, but this is just to let you know that I implemented a custom resolver function to handle uploads. In my case, I did not re-use the CRUDResolver, but maybe you could create a [custom resolver (extending from the CRUDResolver)](https://doug-martin.github.io/nestjs-query/docs/graphql/resolvers/#crudresolver), override the createOne mutation and process the upload field by yourself before calling super.createOne ?

Or actually, now that I think about it, the error comes from class-transformer, maybe you need to add the appropriate [type annotations](https://github.com/typestack/class-transformer#working-with-nested-objects) to the GraphQLUpload input field?

**Comment by ridyio** [comment]
@luca-nardelli Thanks for your suggestion and it seems a good solution for this. For my case after spending two days trying to fix this i gave up and used a REST endpoint for upload instead. This solution you mentioned here could as well help others. I opened the issue just before i gave up :)
Also i have heard there is a consideration about upload putting pressure on GraphQL server and REST not being a bad choice for upload instead.
