### ISSUE TITLE
Seems like OR logic is messed up, wrong SQL is generated

### ISSUE THREAD

**Issue by thehappycoder** [doug-martin/nestjs-query#895]
Is it a known issue (hard to search something like that)? If not, I'll post more info.

Basically, SQL is generated with a OR b not enclosed in (), and when I add more filters with AND, this is what I get: `a OR b AND c` (in pseudocode) but should get `(a OR b) AND c`

**Comment by doug-martin** [comment]
@thehappycoder I'm not aware of this issue, if you could provide some more information that could help me track it down. If you could provide a complete example, along with info on the packages you are using I would appreciate it!

Thanks for reporting!

**Comment by thehappycoder** [comment]
@doug-martin False alarm but maybe a good indicator that documentation should mention this gotcha. To "fix" this, I had to wrap "or" inside "and":

```{
    "status":{"eq":"SUBMITTED"},
    "and": {
      "or": [
        {"prefColor":{"iLike":"%no preference%"}},
        {"prefColor":{"iLike":"%no real preference%"}},
        {"prefColor":{"iLike":"%no strong preference%"}},
        {"prefColor":{"iLike":"%any%"}},
        {"prefColor":{"iLike":"%open%"}}
      ]
    }
  }
```

**Comment by thehappycoder** [comment]
I probably assumed that AND and OR logic worked like in Prisma, where wrapping or inside and isn't needed as far as I remember (https://www.prisma.io/docs/reference/api-reference/prisma-client-reference/#or), so I got hit by this gotcha.

**Comment by doug-martin** [comment]
@thehappycoder you are right it shouldn't be needed. Which persistence package are you using? Each one is different based on what's required to use the library.

**Comment by thehappycoder** [comment]
@doug-martin  I am using typeorm

**Comment by doug-martin** [comment]
@thehappycoder this has been addressed in `v0.23.1`. Thank you for reporting!

**Comment by vladmelnyk** [comment]
@doug-martin seems like v0.23.1 hasn't been published yet on npm
https://www.npmjs.com/package/@nestjs-query/core

**Comment by doug-martin** [comment]
@vladmelnyk it was just a patch for `@nestjs-query/query-typeorm`. 

Let me know if that works.
