### ISSUE TITLE
Async Hook Function

### ISSUE THREAD

**Issue by incode4it** [doug-martin/nestjs-query#900]
From the definitions, I see that `HookFunc` can return a `Promise`

`export declare type HookFunc<T, Context = any> = (instance: T, context: Context) => T | Promise<T>;`

But If using the` @BeforeCreateOne()` hook that returns a Promise. A validation error will be thrown saying that properties are required. `someEntity validation failed: someField: Path someField is required.`

As a temporary fix, you can use Pipes, which can be async.

**Comment by incode4it** [comment]
UPDATE: As a temporary solution I had to use Pipes.

**Comment by doug-martin** [comment]
@incode4it the current hooks implementation does a transform and validate before calling the user provided hook. It sounds like the incoming DTO does not have the required fields and is failing in `class-validator`. I'm curious do you have have a [global validation pipe](https://docs.nestjs.com/techniques/validation#auto-validation) enabled? 

P.S. In the next version of nestjs-query the hooks have been completely re-written and no longer do validation as part of the hook, there were a couple of reasons for this, but in short I would recommend [turning on the global validation pipe](https://docs.nestjs.com/techniques/validation#auto-validation)

**Comment by doug-martin** [comment]
@incode4it I have just released the latest version that has tests around async hooks, as well as the removal of the validation call. Please let me know if you run into any additional issues.
