### ISSUE TITLE
Unexpected testing behavior with NoOpQueryService

### ISSUE THREAD

**Issue by brandon-lile** [doug-martin/nestjs-query#917]
**Describe the bug**
I'm having issues getting services that extend the `NoOpQueryService` to return the correct results in tests. 

For some background on why we are using `NoOpQueryService`: One of the solutions that we have in place is to allow consumers to write a GraphQL query that then backends to an API. The API's response is then parsed in the service and returned to the user. Since this service has no need for a database connection and we only want certain functions defined, it was built using a `NoOpQueryService`.

I was attempting to write a test for the `CRUDResolver` that consumes this `NoOpQueryService`, but I could not get the results of the `CRUDResolver.queryMany` to match up with the mock, or even the dummy data in the service.

I've created a repository with a reproducible setup here: https://github.com/brandon-lile/nestjs-query-example

Just to ensure clarity on what I'm having issues with, here's a better outline:

Let's say that I have a `TodoItemResolver` that looks like this:
```typescript
@Resolver()
export class TodoItemResolver extends CRUDResolver(TodoItemDTO, {}) {
  constructor(readonly todoItemService: TodoItemService) {
    super(todoItemService);
  }
}
```

and a `TodoItemService` that looks like this:
```typescript
@Injectable()
export class TodoItemService extends NoOpQueryService<TodoItemDTO> {
  private todoItems: TodoItemDTO[] = [];

  constructor() {
    super();

    this.todoItems = [
      {
        id: 1,
        title: 'Test Title',
        completed: false,
        created: new Date(),
        updated: new Date(),
      },
    ];
  }

  query(query: Query<TodoItemDTO>): Promise<TodoItemDTO[]> {
    return Promise.resolve(applyQuery(this.todoItems, query));
  }
}
```

In a test where I am calling `resolver.queryMany({ filter: { id: { eq: 1 } } }).edges` I would expect to get that dummy data in the service as a response, but that is not what I'm seeing.

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?

Yes

**To Reproduce**
1. Clone repository with example code: https://github.com/brandon-lile/nestjs-query-example
2. Run `npm install`
3. Run `npm run test`

**Expected behavior**
**Overview:** I provided two tests in the repository and originally I would have expected the "not mocked" version of the test to work, but in reality, neither of them work. 
**Mocked test details:** Since I mocked the underlying `query` function in the service, I would expect that the return value that I mocked out would be the one returned
**Unmocked test details:** Since nothing was mocked, I would expect that the dummy data defined in the service would be returned.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Node Verson: v12.11.1
 - Nestjs-query Version: v0.21.2

**Additional context**

**Comment by doug-martin** [comment]
Hi @brandon-lile!

Looking at your test it looks to me like its the way you're using the testing module the [nestjs testing docs](https://docs.nestjs.com/fundamentals/testing#end-to-end-testing) briefly touch on this but what I think you are looking for is the `overrideProvider` method.

Try the following

```ts
 beforeEach(async () => {
    queryMock = jest.fn(async () => {
      return Promise.resolve([mockedTodoItem]);
    });

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        TodoItemService,
        TodoItemResolver,
      ],
    })
   .overrideProvider(TodoItemService)
   .useValue({query: queryMock})
   .compile();

    resolver = module.get<TodoItemResolver>(TodoItemResolver);
  });

```

**Comment by doug-martin** [comment]
You can also take a look at how I do a very similar thing for all of my tests for the graphql package https://github.com/doug-martin/nestjs-query/blob/master/packages/query-graphql/__tests__/resolvers/__fixtures__/index.ts#L24

**Comment by brandon-lile** [comment]
Thank you so much!
