### ISSUE TITLE
Getting a field using microservice ClientProxy

### ISSUE THREAD

**Issue by Flusinerd** [doug-martin/nestjs-query#932]
Hello, I want to be able to fetch the ``owner`` of my entites using a microservice client that talks to my login microservice.

All entites extend from the base class ``Resource``:
```ts
@InterfaceType()
export abstract class Resource {
  @Column('uuid')
  @Field(() => ID)
  @IsUUID()
  ownerId: string;

  @Field(() => User)
  owner: User;
``` 
``User`` can only be retrieved via a ``ClientProxy``:
```ts
return loginService.send('get_user', {
            secret: this._configService.get('CLIENT_SECRET'),
            userId: resource.ownerId,
          });
 ```
 
 
 This worked with the "vanilla" nestjs ``ResolveField`` decorator:
 ```ts
  @ResolveField(() => User)
  async owner(@Parent() project: Project) {
    console.log('Getting user', project.ownerId);
    return await this.loginService.send('get_user', {
      secret: this._configService.get('CLIENT_SECRET'),
      userId: project.ownerId,
    });
  }
```

How would I be able to achieve something similar with this package?
Ideally it is attached to the ``Resource`` Entity / DTO.
It can be readonly.

**Comment by Jermorin** [comment]
@Flusinerd I'm interesting to know how you solve this issue ?
