### ISSUE TITLE
Group by with aggregation ?

### ISSUE THREAD

**Issue by moioo91120** [doug-martin/nestjs-query#952]
Hello,

Is there any way to use a group by along with the aggregation part ?

Thanks,

**Comment by doug-martin** [comment]
@moioo91120 I just added this in `v0.25.0` you can read about the new feature [here](https://github.com/doug-martin/nestjs-query/discussions/1034) 

Thank you for the feature request!

**Comment by moioo91120** [comment]
Nice !
