### ISSUE TITLE
Subscription "Authorizer"

### ISSUE THREAD

**Issue by luca-nardelli** [doug-martin/nestjs-query#958]
**Is your feature request related to a problem? Please describe.**
Situation: A user can have many projects, each project has 1 user.
The user subscribes to one of the `createProject` or `updateOneProject` subscriptions without specifying any client-side filter.
Ideally, the user should receive only updates for their projects, but with the current setup of subscriptions they would receive ALL updates/creations events.

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?
yes

**Describe the solution you'd like**
A mechanism similar to the Authorize decorator for subscriptions, or something similar to Hooks (where we can also use Injectable classes!)

**Describe alternatives you've considered**
At the moment, I am implementing my own subscription endpoints, creating a custom filter function that adds some default parameters given the context.

**Additional context**
If I have understood the code correctly, the limitation comes from the fact that the filter for the subscription endpoint is generated by `createSubscriptionFilter` and that function does not have any hooks that can be used to customize its behavior, it justs uses the filters specified during subscription creation.

Assuming there is interest for such a feature, I could probably work on a PR for this!

**Comment by asorian0** [comment]
hi @luca-nardelli I'm facing this fact as a security issue actually, so any user with a valid token can forge a request to sneak into other users subscriptions. Could you please share the approach you're taking as a workaround?
@doug-martin is this feature something you could consider to include?

**Comment by smolinari** [comment]
I believe (and totally theoretical on my part), to make subscriptions work, you should be designing a real-time pipeline of events from whatever object you desire (i.e. projects, tasks, issues, etc.). This pipeline (or message queue) is what is subscribed to along with the user specifics, thus making the resolver its own event queue subscriber. In other words, you need a layer of message queuing below the resolver to be able to message back to the right users. I'd also be very wary of the scaling concerns this use case brings with it too. 

Also, a subscription to updates of particular records for a particular user is one thing. A subscription to the creation of records is another. The user to send a project creation message to can't be determined upfront, unless there is some sort of higher order object controlling the destination for the event message. By that I mean, something like a team the user belongs to or an organization the team belongs to (or both). At any rate, this makes the logic of filtering of the subscribers even more difficult and thus, why I think there needs to be a good bit of business logic involved and not just a simple filter mechanism within nestjs-query. If you read about Facebook's use of Relay and subscriptions, they also note how they use a message queue within the business logic layer for subscriptions.  

Scott

**Comment by asorian0** [comment]
You're right @smolinari, worked on a fix yesterday that basically defines specific channels if authorizer filter exists. Will create a PR asap for the case @doug-martin would like to include it

**Comment by luca-nardelli** [comment]
Hi @asorian0, sorry for the delay in asnwering.

So, what I basically did was to implement my own subscription function using the standard subscription handler from NestJS. This means, however, that I am NOT using the standard filters from nestjs-query. My proposal here was to add a way to merge these "computed" filters with the ones provided by the user, similarly to how it works in queries.

```ts
@Subscription(() => ProjectReadDto, {
    name: ProjectEvents.updateOne,
    async filter(this: ProjectResolver, payload, variables, context) {
      const appContext = getAppContext(context);
      return await this.filterProjectSubscriptions(payload[ProjectEvents.updateOne], appContext);
    },
  })
  updatedOneSubscription(): AsyncIterator<UpdatedEvent<ProjectReadDto>> {
    return this.pubSub.asyncIterator(ProjectEvents.updateOne);
  }
  
  private async filterProjectSubscriptions(project: ProjectEntity, context: AppContext) {
    if (context.user.role === UserRole.admin) {
      return true;
    }
    return context.user.customer.id === project.customerId;
  }
  
```  

I have quickly pasted my code here, let me know if it is unclear. With this basically every user that subscribes to `updatedOneProject` only gets their own events.

**Comment by asorian0** [comment]
Hi @luca-nardelli @smolinari I've created a PR with the solution I was talking about some time ago, strongly inspired on @smolinari comment above.

**Comment by asorian0** [comment]
@doug-martin this issue can be closed though. @luca-nardelli @smolinari solution in https://github.com/doug-martin/nestjs-query/pull/1160 was introduced in `v0.28.1-rc`

**Comment by doug-martin** [comment]
Thanks for the reminder! I'm going through and cleaning up all of the old dependencies and issues over the week or so.
