### ISSUE TITLE
ConnectionType init issues after update 0.23.1 -> 0.24.0

### ISSUE THREAD

**Issue by vladmelnyk** [doug-martin/nestjs-query#973]
**Describe the bug**
After updating to 0.24.0 getting this kind of error
` 'ConnectionType' only refers to a type, but is being used as a value here.`

Code used from doc: https://doug-martin.github.io/nestjs-query/docs/graphql/types/#connectiontype

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

**To Reproduce**
1. Step 1
2. Step 2

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Node Verson [e.g. 14.14.0]
 - Nestjs-query Version [e.g. v0.21.0]

**Additional context**

**Comment by doug-martin** [comment]
@vladmelnyk Thank you for pointing that out, I thought I got all the references :) I've updated the docs with how to get the reference to the ConnectionType and a migration guide.

* https://doug-martin.github.io/nestjs-query/docs/graphql/types/#connectiontype
* https://doug-martin.github.io/nestjs-query/docs/migration-guides/v0.23.x-to-v0.24.x

Thank you for submitting an issue!
